/**
 * agent-text.json (agent markers, agent-written tasks, line anchors) and merge.json (line diffs
 * and three-way merges of notes).
 */
import fc from "fast-check";
import type { ParsedTask } from "../../../../packages/core/src/index.ts";
import { type CoreModule, isWellFormed, sample } from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

// ── Agent markers ───────────────────────────────────────────────────────────────────────────────

const CURATED_LINES = [
  "- Booked %%agent:thr_1%%",
  "  - Trattoria Sole has a table at 7pm ([OpenTable](https://booking.example/r/1)) %%agent:thr_ab12%%",
  "- [ ] Call the restaurant to confirm %%agent:thr_9%%",
  "## Trip to Lisbon %%agent:thr_2%%",
  "- mine",
  "%%agent%% in the middle is not a marker",
  "- ok %%agent%%  ",
  "- ok %%agent:t%%",
  "%%agent%%",
  "%%agent:x%%\t",
  "   %%agent%%",
  "a%%agent%%",
  "- a %%agent%%\n",
  "- a %%agent:%%",
  "- a %%agent:%%agent%%",
  "- a %%agent:agent%%",
  "- a %%agent:thr.1%%",
  "- a %%Agent%%",
  "- a %%agent%% %%",
  "- a %%agent%%%%agent%%",
  `- a %%agent:${"a".repeat(64)}%%`,
  `- a %%agent:${"a".repeat(65)}%%`,
  "🎉 party\t %%agent%%",
  "\u00a0%%agent%%",
  "- nbsp\u00a0 %%agent%%",
  "",
  "   ",
  "\u00a0",
  "- z\t \t",
  "- x %%agent:thr_old%%",
];

const idArb = fc.constantFrom(
  "thr_1",
  "thr_ab12",
  "t",
  "x-y_z",
  "a".repeat(64),
  "a".repeat(65),
  "",
  "bad id",
  "agent",
);
const lineArb = fc
  .tuple(
    fc.constantFrom("", "- ", "  - ", "- [ ] ", "- [x] ", "## ", "> ", "1. "),
    fc.constantFrom("Book a table", "", "🎉 party", "café", "[[Note]]", "x", "%%", "%%agent"),
    fc.constantFrom("", " ", "\t", "  ", "\u00a0"),
    fc.oneof(
      idArb.map((id) => `%%agent:${id}%%`),
      fc.constant("%%agent%%"),
      fc.constant(""),
      fc.constant("%%agent%"),
      fc.constant("%agent%%"),
    ),
    fc.constantFrom("", " ", "\t ", "x"),
  )
  .map((parts) => parts.join(""));

const MARK_IDS: Array<string | null> = [null, "thr_1", "", "not a valid id!", "a".repeat(64)];

// ── Agent-written tasks and line anchors ───────────────────────────────────────────────────────

const CURATED_DOCS = [
  "- [ ] Call the restaurant to confirm %%agent:thr_9%%\n- [ ] Mine\n  - note %%agent%%",
  "- [ ] %%agent:thr_1%%\n- [x] Read [[Note]] %%agent%%\n- [ ] a%%agent%%",
  "- [ ] a\n  %%agent%%",
  [
    "# Thursday",
    "- [ ] Book a table for Friday dinner",
    "  - Trattoria Sole has a table for 2 at 7:00 PM ([OpenTable](https://booking.example/r/1)) %%agent:thr_ab12%%",
    "What's the tallest building in NYC?",
    "- [ ] Call the restaurant to confirm %%agent:thr_ab12%%",
    "",
    "## Trip to Lisbon %%agent:thr_2%%",
  ].join("\n"),
  "- [ ] crlf %%agent:thr_1%%\r\n  - note %%agent%%\r\nprose %%agent%%\r\n",
  "```\n- [ ] in code %%agent%%\n```\n- [ ] after %%agent:thr_1%%",
];

const docLineArb = fc.oneof(
  lineArb,
  fc.constantFrom("", "- [ ] plain task", "  - plain note", "Plain prose", "## Heading", "```"),
);
const docArb = fc
  .array(docLineArb, { minLength: 1, maxLength: 10 })
  .map((lines) => lines.join("\n"));

/** `[anchorId, text, line]`. */
type AnchorRow = [string, string, number];

function anchorCases(core: CoreModule, doc: string, seed: number) {
  const lines = core.anchorableLines(doc);
  // Anchors taken from the document itself, then the document edited around and inside them.
  const edits = [
    doc,
    `- [ ] New task on top\n${doc}`,
    doc.replace(/\n/, "\n\n"),
    doc.replace(/a/g, "A"),
    doc
      .split("\n")
      .filter((_, i) => i % 3 !== 1)
      .join("\n"),
    doc.split("\n").reverse().join("\n"),
  ];
  const anchors: AnchorRow[] = lines.map((l, i) => [
    i % 5 === 4 ? "" : `anc_${seed}_${i}`,
    l.text,
    l.line,
  ]);
  return edits.map((edited) => ({
    doc: edited,
    anchors,
    resolved: Object.fromEntries(
      [
        ...core.resolveLineAnchors(
          edited,
          anchors.map(([anchorId, text, line]) => ({ anchorId, text, line })),
        ),
      ].map(([id, where]) => [id, [where.line, where.text]]),
    ),
  }));
}

export function buildAgentTextVectors(core: CoreModule) {
  const lines = [...CURATED_LINES, ...sample(lineArb, 10_001, 200)]
    .filter(isWellFormed)
    .map((line) => {
      const parsed = core.parseAgentLine(line);
      return {
        line,
        parsed: parsed && [parsed.text, parsed.threadId, parsed.markerFrom],
        stripped: core.stripAgentMarker(line),
        marked: MARK_IDS.map((id) => [id, core.markAgentLine(line, id)]),
      };
    });
  const markers = MARK_IDS.map((id) => [id, core.agentMarker(id)]);
  const documents = [...CURATED_DOCS, ...sample(docArb, 10_002, 80)]
    .filter(isWellFormed)
    .map((doc) => ({
      doc,
      tasks: core.parseTasks(doc).map((t: ParsedTask) => ({
        line: t.line,
        text: t.text,
        raw: t.raw,
        textFrom: t.textFrom,
        notes: t.notes,
        links: t.links,
        agent: t.agent ?? false,
      })),
      anchorable: core.anchorableLines(doc).map((l) => [l.line, l.text]),
    }));
  const anchors = [...CURATED_DOCS, ...sample(docArb, 10_003, 40)]
    .filter(isWellFormed)
    .flatMap((doc, i) => anchorCases(core, doc, i));
  return { about: ABOUT, lines, markers, documents, anchors };
}

// ── Merges ─────────────────────────────────────────────────────────────────────────────────────

const mergeLineArb = fc.constantFrom(
  "- [ ] a",
  "- [ ] b",
  "text",
  "",
  "## h",
  "  - note",
  "  - found it %%agent:thr_1%%",
  "caf\u00e9",
  "cafe\u0301",
  "line\r",
);
const mergeDocArb = fc.array(mergeLineArb, { maxLength: 12 });
const editArb = fc.record({
  kind: fc.constantFrom("insert", "delete", "replace"),
  at: fc.nat(),
  lines: fc.array(mergeLineArb, { minLength: 1, maxLength: 3 }),
});
type LineEdit = { kind: string; at: number; lines: string[] };

function applyEdits(base: readonly string[], edits: readonly LineEdit[]): string[] {
  let lines = [...base];
  for (const edit of edits) {
    const at = lines.length === 0 ? 0 : edit.at % (lines.length + (edit.kind === "insert" ? 1 : 0));
    if (edit.kind === "insert") lines = [...lines.slice(0, at), ...edit.lines, ...lines.slice(at)];
    else if (edit.kind === "delete") lines = [...lines.slice(0, at), ...lines.slice(at + 1)];
    else lines = [...lines.slice(0, at), ...edit.lines, ...lines.slice(at + 1)];
  }
  return lines;
}

const tripleArb = fc.tuple(
  mergeDocArb,
  fc.array(editArb, { maxLength: 3 }),
  fc.array(editArb, { maxLength: 3 }),
);

const CURATED_MERGES: Array<[string, string, string]> = [
  [
    "# Thursday\n- [ ] Book a table\n- [ ] Renew passport\nNotes",
    "# Thursday\n- [ ] Book a table for two\n- [ ] Renew passport\nNotes",
    "# Thursday\n- [ ] Book a table\n  - Trattoria Sole has a table at 7pm %%agent:thr_1%%\n- [ ] Renew passport\nNotes",
  ],
  ["a\nb\nc", "a\nb\nc\nlocal", "a\nb\nc\nremote"],
  ["a\nb\nc", "a\nB\nc", "a\nb2\nc"],
  ["a\nb\nc", "a\nc", "a\nb\nc!"],
  ["", "x", "y"],
  ["a\n", "a\nb\n", "a\n\nc"],
  ["x\ny", "x\ny", "x\ny"],
];

export function buildMergeVectors(core: CoreModule) {
  const diffs = sample(
    fc.tuple(
      fc.array(fc.constantFrom("a", "b", "c", "d"), { maxLength: 30 }),
      fc.array(fc.constantFrom("a", "b", "c", "d"), { maxLength: 30 }),
    ),
    10_004,
    200,
  ).map(([a, b]) => ({
    a,
    b,
    hunks: core.diffLines(a, b).map((h) => [h.start, h.end, h.lines]),
  }));
  const triples: Array<[string, string, string]> = [
    ...CURATED_MERGES,
    ...sample(tripleArb, 10_005, 400).map(([base, mine, theirs]): [string, string, string] => [
      base.join("\n"),
      applyEdits(base, mine).join("\n"),
      applyEdits(base, theirs).join("\n"),
    ]),
  ];
  const merges = triples.map(([base, local, remote]) => {
    const { text, conflict } = core.mergeText(base, local, remote);
    return { base, local, remote, text, conflict };
  });
  return { about: ABOUT, diffs, merges };
}
