/** daily-notes.json and template.json. */
import fc from "fast-check";
import type { DailyNoteSettings, WeeklyNoteSettings } from "../../../../packages/core/src/index.ts";
import {
  type CoreModule,
  date,
  dateArb,
  fromYmd,
  isWellFormed,
  PINNED_NOW_MS,
  sample,
  uniqueBy,
  VECTOR_TIME_ZONE,
  type YMD,
  ymd,
} from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

const FOLDERS = [
  "Daily",
  "",
  "/",
  "Daily/",
  "/Daily/",
  "./Journal//Daily",
  "Notes\\Daily",
  "Café/日記",
  "Journal/Cafe\u0301",
  "My Notes",
  "a/b/c/d",
];

const FORMATS = [
  "YYYY-MM-DD",
  "",
  "YYYY/MM/YYYY-MM-DD",
  "YYYY/MM-MMMM/YYYY-MM-DD dddd",
  "YYYY/[Q]M/DD",
  "gggg/[W]ww/YYYY-MM-DD",
  "GGGG/[W]WW/YYYY-MM-DD ddd",
  "DD.MM.YYYY",
  "[Daily ]YYYY-MM-DD",
  "dddd, MMMM Do YYYY",
  "MMM D, YYYY",
  "YYYY-DDDD",
  "YYYYMMDD",
  "GGGG-[W]WW-E",
  "YYYY-MM-DD[.md]",
  "YYYY-MM-DD[.MD]",
];

/** Settings that make the TypeScript core throw (a path escaping the vault). */
const ESCAPING: DailyNoteSettings[] = [
  { folder: "", format: "[../]YYYY", template: "" },
  { folder: "../Outside", format: "YYYY-MM-DD", template: "" },
  { folder: "Daily/../..", format: "YYYY-MM-DD", template: "" },
  { folder: "Daily", format: "[../../]YYYY-MM-DD", template: "" },
  { folder: "Daily", format: "[..]", template: "" },
];

interface DailyNoteVectors {
  about: string;
  timeZone: string;
  settings: DailyNoteSettings[];
  /** `[settings index, date, dailyNotePath(date, settings) | null, error name | null]`. */
  paths: Array<[number, YMD, string | null, string | null]>;
  /** `[settings index, path, parseDailyNotePath(path, settings) | null, error name | null]`. */
  parse: Array<[number, string, YMD | null, string | null]>;
  adjacent: Array<{
    settings: number;
    paths: string[];
    from: YMD;
    direction: -1 | 1;
    result: { path: string; date: YMD } | null;
  }>;
  list: Array<{ settings: number; paths: string[]; result: Array<{ path: string; date: YMD }> }>;
  navigation: Array<{ settings: number; activePath: string | null; now: number; date: YMD }>;
  templatePath: Array<[string, string | null]>;
  weekly: Array<{ settings: WeeklyNoteSettings; date: YMD; path: string }>;
  /** `[date, from, pastDays, futureDays, isWithinWindow(...)]`. */
  window: Array<[YMD, YMD, number, number, boolean]>;
}

function attempt<T>(fn: () => T): { value: T | null; error: string | null } {
  try {
    return { value: fn(), error: null };
  } catch (error) {
    return { value: null, error: error instanceof Error ? error.name : "Error" };
  }
}

export function buildDailyNoteVectors(core: CoreModule): DailyNoteVectors {
  const settings: DailyNoteSettings[] = [];
  for (const folder of FOLDERS) settings.push({ folder, format: "YYYY-MM-DD", template: "" });
  for (const format of FORMATS) settings.push({ folder: "Daily", format, template: "" });
  settings.push(
    { folder: "", format: "YYYY/MM/YYYY-MM-DD", template: "" },
    { folder: "Journal", format: "gggg/[W]ww/YYYY-MM-DD", template: "" },
    { folder: "Café/日記", format: "dddd, MMMM Do YYYY", template: "" },
    ...ESCAPING,
  );
  const settingsIndex = (s: DailyNoteSettings) => settings.indexOf(s);

  const dates: YMD[] = uniqueBy(
    [
      date(2026, 9, 23),
      date(2026, 1, 1),
      date(2025, 12, 28),
      date(2024, 2, 29),
      date(2020, 12, 31),
      date(2021, 1, 3),
      date(1900, 1, 1),
      date(2100, 12, 31),
      ...sample(dateArb(1900, 2100), 2001, 12).map(ymd),
    ],
    (d) => d,
  );

  const paths: DailyNoteVectors["paths"] = [];
  const parse: DailyNoteVectors["parse"] = [];
  const addParse = (index: number, path: string) => {
    const r = attempt(() => core.parseDailyNotePath(path, settings[index]!));
    parse.push([index, path, r.value ? ymd(r.value) : null, r.error]);
  };
  settings.forEach((s, index) => {
    dates.forEach((d, i) => {
      const r = attempt(() => core.dailyNotePath(fromYmd(d), s));
      paths.push([index, d, r.value, r.error]);
      if (r.value !== null && i % 3 === 0) {
        addParse(index, r.value);
        addParse(index, r.value.replace(/\.md$/, ".MD"));
        addParse(index, r.value.replace(/\.md$/, ".txt"));
        addParse(index, `Elsewhere/${r.value}`);
        addParse(index, r.value.normalize("NFD"));
      } else if (r.value !== null) {
        addParse(index, r.value);
      }
    });
  });
  const noise = [
    "Daily/notes.md",
    "Daily/2026-02-30.md",
    "Projects/2026-09-20.md",
    "Daily/2026-09-20.txt",
    "Daily/Archive/2026-09-21.md",
    "2026-09-22.md",
    "daily/2026-09-23.md",
    "Daily/2026-09-23.md.md",
    "Daily/2026-09-23",
    "Daily/.md",
    "Daily/2026-09-23 .md",
    "Dailyish/2026-09-23.md",
    "",
    ".md",
  ];
  settings.forEach((_, index) => {
    for (const path of noise) addParse(index, path);
  });

  const nav = settings[0]!;
  const narrow = dateArb(2026, 2026).filter((d) => d.month >= 8 && d.month <= 10);
  const noiseArb = fc.constantFrom(...noise.slice(0, 6));
  const pathListArb = fc.array(
    fc.oneof(
      narrow.map((d) => core.dailyNotePath(d, nav)),
      narrow.map((d) => core.dailyNotePath(d, nav).replace(/\.md$/, ".MD")),
      noiseArb,
    ),
    { maxLength: 25 },
  );
  const adjacentCases = sample(
    fc.tuple(pathListArb, narrow, fc.constantFrom<-1 | 1>(-1, 1)),
    2002,
    80,
  );
  const gapPaths = [
    "Daily/2026-09-18.md",
    "Daily/2026-09-21.md",
    "Daily/2026-09-22.md",
    "Daily/2026-09-25.md",
    "Projects/2026-09-20.md",
    "Daily/readme.md",
  ];
  const curatedAdjacent: Array<[string[], YMD, -1 | 1]> = [
    [gapPaths, date(2026, 9, 21), -1],
    [gapPaths, date(2026, 9, 22), 1],
    [gapPaths, date(2026, 9, 18), -1],
    [gapPaths, date(2026, 9, 25), 1],
    [gapPaths, date(2026, 9, 1), 1],
    [gapPaths, date(2026, 12, 1), -1],
    [["Daily/2026-09-21.md", "Daily/2026-09-21.MD"], date(2026, 9, 22), -1],
    [[], date(2026, 9, 22), 1],
  ];
  const adjacent: DailyNoteVectors["adjacent"] = [];
  const addAdjacent = (list: string[], from: YMD, direction: -1 | 1) => {
    const r = core.findAdjacentDailyNote(list, fromYmd(from), direction, nav);
    adjacent.push({
      settings: settingsIndex(nav),
      paths: list,
      from,
      direction,
      result: r ? { path: r.path, date: ymd(r.date) } : null,
    });
  };
  for (const [list, from, direction] of curatedAdjacent) addAdjacent(list, from, direction);
  for (const [list, from, direction] of adjacentCases) addAdjacent(list, ymd(from), direction);
  const nested = settings.find((s) => s.format === "YYYY/MM/YYYY-MM-DD" && s.folder === "")!;
  const nestedList = ["2026/09/2026-09-01.md", "2026/08/2026-08-31.md", "2025/12/2025-12-31.md"];
  const r = core.findAdjacentDailyNote(nestedList, { year: 2026, month: 9, day: 1 }, -1, nested);
  adjacent.push({
    settings: settingsIndex(nested),
    paths: nestedList,
    from: date(2026, 9, 1),
    direction: -1,
    result: r ? { path: r.path, date: ymd(r.date) } : null,
  });

  const sameDay = ["Daily/2026-09-21.MD", "Daily/2026-09-20.md", "Daily/2026-09-21.md"];
  const list = [...sample(pathListArb, 2003, 30), gapPaths, sameDay].map((items) => ({
    settings: settingsIndex(nav),
    paths: items,
    result: core.listDailyNotes(items, nav).map((n) => ({ path: n.path, date: ymd(n.date) })),
  }));

  const nowArb = fc.integer({ min: Date.UTC(2000, 0, 1), max: Date.UTC(2040, 0, 1) });
  const navigation: DailyNoteVectors["navigation"] = [];
  const addNavigation = (activePath: string | null, now: number) =>
    navigation.push({
      settings: settingsIndex(nav),
      activePath,
      now,
      date: ymd(core.navigationAnchorDate(activePath, nav, new Date(now))),
    });
  addNavigation("Daily/2026-09-21.md", PINNED_NOW_MS);
  addNavigation("Ideas.md", PINNED_NOW_MS);
  addNavigation(null, PINNED_NOW_MS);
  addNavigation("", PINNED_NOW_MS);
  addNavigation(null, Date.UTC(2026, 0, 1, 7, 59, 59));
  addNavigation(null, Date.UTC(2026, 0, 1, 8));
  for (const [d, now, useNote] of sample(
    fc.tuple(dateArb(1900, 2100), nowArb, fc.boolean()),
    2004,
    30,
  )) {
    addNavigation(useNote ? core.dailyNotePath(d, nav) : "Projects/Plan.md", now);
  }

  const templates = [
    "Templates/Daily",
    "Templates/Daily.md",
    "  /Templates//Daily.MD ",
    "",
    "   ",
    "Templates\\Weekly",
    "./T/../Daily",
    "\tTemplates/Daily\n",
  ];

  const weeklySettings: WeeklyNoteSettings[] = [
    { folder: "Weekly/", format: "", template: "" },
    { folder: "Weekly", format: "gggg-[W]ww", template: "" },
    { folder: "", format: "GGGG-[W]WW", template: "" },
    { folder: "Reviews", format: "gggg/[Week] w", template: "" },
  ];
  const weekly: DailyNoteVectors["weekly"] = [];
  for (const s of weeklySettings) {
    for (const d of dates)
      weekly.push({ settings: s, date: d, path: core.weeklyNotePath(fromYmd(d), s) });
  }

  const window = sample(
    fc.tuple(dateArb(1900, 2100), dateArb(1900, 2100), fc.nat({ max: 400 }), fc.nat({ max: 400 })),
    2005,
    60,
  ).map(([d, from, past, future]): [YMD, YMD, number, number, boolean] => [
    ymd(d),
    ymd(from),
    past,
    future,
    core.isWithinWindow(d, from, past, future),
  ]);
  const edge = { year: 2026, month: 9, day: 23 };
  for (const [d, past, future] of [
    [{ year: 2026, month: 9, day: 23 }, 0, 0],
    [{ year: 2026, month: 9, day: 30 }, 0, 7],
    [{ year: 2026, month: 10, day: 1 }, 0, 7],
    [{ year: 2026, month: 9, day: 22 }, 0, 7],
    [{ year: 2026, month: 9, day: 22 }, 1, 0],
  ] as const) {
    window.push([ymd(d), ymd(edge), past, future, core.isWithinWindow(d, edge, past, future)]);
  }

  return {
    about: ABOUT,
    timeZone: VECTOR_TIME_ZONE,
    settings,
    paths,
    parse,
    adjacent,
    list,
    navigation,
    templatePath: templates.map((t) => [t, core.templateNotePath({ template: t })]),
    weekly,
    window,
  };
}

interface TemplateVectors {
  about: string;
  timeZone: string;
  cases: Array<{
    template: string;
    title: string;
    date: YMD;
    now: number;
    dateFormat: string | null;
    timeFormat: string | null;
    output: string;
  }>;
}

const TEMPLATES = [
  "# {{title}}\n{{date:dddd}} {{date}} {{time}} {{unknown}}",
  "{{title}}",
  "{{ title }}",
  "{{TITLE}} {{Date}} {{TiMe}}",
  "{{date:}} {{ title",
  "{{date:YYYY-MM-DD}}",
  "{{date: dddd, MMMM Do }}",
  "{{date:   }}",
  "{{date: }}",
  "{{ date : [Week] ww }}",
  "{{time:HH:mm:ss}}",
  "{{time: h A }}",
  "{{time:X}} {{time:x}}",
  "{{{title}}}",
  "{{{{date}}}}",
  "{{date}}}}",
  "{{date}",
  "{date}}",
  "{{title:ignored format}}",
  "{{date:DD MM}}",
  "{{date:YYYY}{MM}}",
  "{{date:YYYY}",
  "{{ date:gggg-[W]ww }} {{date:GGGG-[W]WW}}",
  "{{date\t:\tYYYY\t}}",
  "{{\u00a0date\u00a0}}",
  "{{\ndate\n}}",
  "{{ datetime }}",
  "{{date:\u2028YYYY}}",
  "Line 1\r\n{{date}}\r\n- [ ] {{title}}",
  "$& $1 {{title}} $' $`",
  "{{date:[{{title}}]}}",
  "{{title}}{{title}}{{title}}",
  "",
];

export function buildTemplateVectors(core: CoreModule): TemplateVectors {
  const contexts: Array<{
    title: string;
    date: YMD;
    now: number;
    dateFormat?: string;
    timeFormat?: string;
  }> = [
    { title: "2026-09-23", date: date(2026, 9, 23), now: Date.UTC(2026, 8, 23, 14, 5) },
    {
      title: "$& {{date}} $1",
      date: date(2026, 9, 23),
      now: Date.UTC(2026, 8, 23, 14, 5),
      dateFormat: "DD/MM",
      timeFormat: "h A",
    },
    { title: "Café 日記 🎉", date: date(2025, 12, 28), now: Date.UTC(2026, 0, 1, 7, 59, 59) },
    {
      title: "",
      date: date(2024, 2, 29),
      now: Date.UTC(2026, 2, 8, 10),
      dateFormat: "",
      timeFormat: "",
    },
  ];
  const random = sample(
    fc.record({
      title: fc.string({ unit: "grapheme", maxLength: 20 }),
      date: dateArb(1900, 2100).map(ymd),
      now: fc.integer({ min: Date.UTC(2000, 0, 1), max: Date.UTC(2040, 0, 1) }),
    }),
    3001,
    6,
  );
  const cases: TemplateVectors["cases"] = [];
  const all: Array<(typeof contexts)[number]> = [...contexts, ...random];
  for (const ctx of all) {
    if (!isWellFormed(ctx.title)) continue;
    for (const template of TEMPLATES) {
      const full = { ...ctx, date: fromYmd(ctx.date), now: new Date(ctx.now) };
      cases.push({
        template,
        title: ctx.title,
        date: ctx.date,
        now: ctx.now,
        dateFormat: ctx.dateFormat ?? null,
        timeFormat: ctx.timeFormat ?? null,
        output: core.renderTemplate(template, full),
      });
    }
  }
  return { about: ABOUT, timeZone: VECTOR_TIME_ZONE, cases };
}
