/** paths.json: vault path normalization, helpers and natural ordering. */
import fc from "fast-check";
import { type CoreModule, isWellFormed, sample, uniqueBy } from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

const SEGMENTS = [
  "Daily",
  "notes",
  "a",
  "B",
  "2026-09-23.md",
  "Café",
  "日記",
  "my note.md",
  "x.tar.gz",
  "",
  ".",
  "..",
  "...",
  ". ",
  " ..",
  ".hidden",
  ".daily-do-list",
  ".daily-do-listx",
  ".md",
  ".MD",
  "a.",
  "a\\b",
  "..\\..",
  "%2e%2e",
  "\0",
  "🎉",
  "a b",
  "\u2028",
  "e\u0301",
  "note.Md",
];

const CURATED = [
  "/Daily//2026-09-23.md",
  "a\\b\\..\\c.md",
  "./a/./b/",
  "../etc/passwd",
  "a/../../b",
  "../x",
  "a/b/../../..",
  "a/b/../..",
  "%2e%2e/x",
  "... /x",
  "",
  "/",
  "//",
  "\\\\server\\share",
  ".daily-do-list",
  ".daily-do-list/threads/x.json",
  ".daily-do-listx/y",
  "Daily/.draft.md",
  ".obsidian/app.json",
  "a\0b",
  "Daily/2026-09-23.MD",
  "x.tar.gz",
  ".env",
  "a.",
  "Notes/Cafe\u0301.md",
  "/\u0301x/y",
];

interface PathVectors {
  about: string;
  sidecarDir: string;
  /** `[input, normalizePath(input) | null, error reason | null]`. */
  normalize: Array<[string, string | null, string | null]>;
  helpers: Array<{
    path: string;
    isSafe: boolean;
    dirname: string;
    basename: string;
    extname: string;
    stem: string;
    isMarkdown: boolean;
    ensureMarkdown: string;
    isHidden: boolean;
    isSidecar: boolean;
    ancestors: string[];
  }>;
  /** `[parts, joinPath(...parts) | null, error reason | null]`. */
  join: Array<[string[], string | null, string | null]>;
  /** Locale of the ICU collator behind `localeCompare` when the vectors were made. */
  locale: string;
  /** `[a, b, Math.sign(compareVaultPaths(a, b))]`. */
  compare: Array<[string, string, number]>;
}

function reason(error: unknown): string {
  const message = error instanceof Error ? error.message : String(error);
  if (message.includes("NUL")) return "nul";
  if (message.includes("escapes")) return "escape";
  return message;
}

export function buildPathVectors(core: CoreModule): PathVectors {
  const rawArb = fc
    .tuple(
      fc.array(
        fc.oneof(fc.constantFrom(...SEGMENTS), fc.string({ unit: "grapheme", maxLength: 5 })),
        {
          maxLength: 6,
        },
      ),
      fc.constantFrom("/", "\\", "//"),
      fc.boolean(),
    )
    .map(([segments, sep, leading]) => `${leading ? sep : ""}${segments.join(sep)}`);
  const inputs = uniqueBy([...CURATED, ...sample(rawArb, 4001, 260)], (p) => p).filter(
    isWellFormed,
  );

  const normalize: PathVectors["normalize"] = inputs.map((input) => {
    try {
      return [input, core.normalizePath(input), null];
    } catch (error) {
      return [input, null, reason(error)];
    }
  });

  const helperInputs = uniqueBy(
    [
      ...inputs.filter((_, i) => i % 2 === 0),
      ...normalize.flatMap(([, out]) => (out ? [out] : [])),
    ],
    (p) => p,
  );
  const helpers = helperInputs.map((path) => ({
    path,
    isSafe: core.isSafeVaultPath(path),
    dirname: core.dirname(path),
    basename: core.basename(path),
    extname: core.extname(path),
    stem: core.stem(path),
    isMarkdown: core.isMarkdownPath(path),
    ensureMarkdown: core.ensureMarkdownExtension(path),
    isHidden: core.isHiddenPath(path),
    isSidecar: core.isSidecarPath(path),
    ancestors: core.ancestorFolders(path),
  }));

  const joinCases: string[][] = [
    ["Daily", "2026-09-23.md"],
    ["", "Daily", "", "x.md"],
    ["a/b", "../c"],
    ["a", "../../c"],
    [],
    [""],
    ["/", "/"],
    ["Notes\\Daily", "x.md"],
    ...sample(fc.array(fc.constantFrom(...SEGMENTS), { maxLength: 4 }), 4002, 40),
  ];
  const join: PathVectors["join"] = joinCases.map((parts) => {
    try {
      return [parts, core.joinPath(...parts), null];
    } catch (error) {
      return [parts, null, reason(error)];
    }
  });

  const names = uniqueBy(
    [
      "notes.md",
      "Notes.md",
      "cafe.md",
      "café.md",
      "Day 2.md",
      "Day 10.md",
      "Day 02.md",
      "Day 0.md",
      "a-b",
      "a b",
      "a_b",
      "a.b",
      "a/b",
      "ab",
      "résumé",
      "resume",
      "Straße 2",
      "Strasse 10",
      "strasse",
      "file (1).md",
      "file (10).md",
      "file (2).md",
      "",
      " ",
      "1.5",
      "1.10",
      "v1.2",
      "v1.10",
      "日本",
      "😀",
      "_x",
      "-y",
      "Ä",
      "z",
      "2026-09-23.md",
      "2026-10-01.md",
      "Daily/2026-09-23.md",
      "Daily 2/x.md",
      ...sample(
        fc.oneof(
          fc.string({
            unit: fc.constantFrom("a", "B", "é", "E", "1", "2", "0", " ", "-", ".", "/", "日"),
            maxLength: 8,
          }),
          fc.integer({ min: 0, max: 200 }).map((n) => `note ${n}.md`),
        ),
        4003,
        60,
      ),
    ],
    (n) => n,
  );
  const compare: PathVectors["compare"] = [];
  names.forEach((a, i) => {
    names.forEach((b, j) => {
      if ((i * 7 + j * 3) % 5 === 0) compare.push([a, b, Math.sign(core.compareVaultPaths(a, b))]);
    });
  });
  // ICU sorts ß as "ss"; these pairs catch collators that don't.
  const sharpS = [
    "ßa",
    "ssb",
    "ß/",
    "ss😀",
    "ß0",
    "ssa",
    "ß#",
    "ß ",
    "aß/",
    "ass😀",
    "ssä",
    "ẞx",
    "SSw",
  ];
  for (const a of sharpS) {
    for (const b of sharpS) compare.push([a, b, Math.sign(core.compareVaultPaths(a, b))]);
  }

  return {
    about: ABOUT,
    sidecarDir: core.SIDECAR_DIR,
    normalize,
    helpers,
    join,
    locale: new Intl.Collator().resolvedOptions().locale,
    compare,
  };
}
