/** tasks.json: parseTasks on curated and generated documents, plus the task-line helpers. */
import fc from "fast-check";
import type { ParsedTask, TaskStatus } from "../../../../packages/core/src/index.ts";
import { type CoreModule, isWellFormed, sample } from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

const NOTE = [
  "---",
  "tags: [daily]",
  "- [ ] not a task (frontmatter)",
  "---",
  "- [x] Renew passport -> done at the post office",
  "- [ ] Book dentist appointment - prefer mornings",
  "  - call Dr. Lee first",
  "  - [ ] find insurance card",
  "    extra context line",
  "* [/] Draft Q4 plan",
  "1. [-] Cancelled thing",
  "- [>] Move to [[Daily/2026-09-24]]",
  "",
  "```",
  "- [ ] not a task (code)",
  "```",
  "Some freeform note",
  "- plain bullet",
  "- [ ]",
].join("\n");

/** Frontmatter body with a task-like line, which only counts as a task outside frontmatter. */
const yaml199 = Array.from({ length: 199 }, (_, i) =>
  i === 0 ? "- [ ] inside frontmatter?" : `k${i}: v`,
);

/** Decided behavior from the core's unit and property tests, plus UTF-16 offset traps. */
const CURATED: Array<[string, string]> = [
  ["daily note fixture", NOTE],
  ["empty document", ""],
  ["single newline", "\n"],
  ["only a BOM", "\uFEFF"],
  ["bare box", "- [ ]"],
  ["box with a space", "- [ ] "],
  ["upper-case X", "* [X] upper-case done"],
  ["in progress plus marker", "+ [/] in progress"],
  ["paren marker", "10) [>] forwarded"],
  ["nine-digit marker", "123456789. [ ] nine-digit marker"],
  ["ten-digit marker", "1234567890. [ ] ten-digit marker"],
  ["tab before text", "- [ ]\ttab before text"],
  ["tab indent", "\t- [ ] tab indent"],
  ["trailing spaces", "- [ ] trailing spaces   "],
  ["brackets in text", "- [ ] [ ] brackets in the text"],
  ["line separator in text", "- [ ] line\u2028separator"],
  ["lone CR in text", "- [ ] lone\rCR is not a line break"],
  ["bracket status", "- []] bracket status"],
  ["no space after marker", "-[ ] no space after the marker"],
  ["two spaces in the box", "- [  ] two spaces in the box"],
  ["two characters in the box", "- [xx] two characters in the box"],
  ["glued text", "- [ ]glued text"],
  ["astral status", "- [🎉] astral status (two code units)"],
  ["letter marker", "a. [ ] letter marker"],
  ["heading", "# [ ] heading"],
  ["heading with a task tail", "## - [ ] heading with a task-like tail"],
  ["table cell", "| - [ ] | table cell |"],
  ["quoted task", "> - [ ] quoted task"],
  ["no marker", "[ ] no marker"],
  [
    "status characters",
    [" ", "x", "X", "/", "-", ">", "<", "?", "é", "$"].map((c) => `- [${c}] t`).join("\n"),
  ],
  ["indented four spaces", "Some paragraph\n\n    - [ ] indented four spaces"],
  ["fence closes", "```\n- [ ] in code\n```\n- [ ] after"],
  ["shorter tilde fence does not close", "~~~~\n- [ ] a\n~~~\n- [ ] b\n~~~~\n- [ ] c"],
  ["different fence does not close", "```\n- [ ] a\n~~~\n- [ ] b"],
  ["unterminated indented fence", "- [ ] before\n  ```\n  - [ ] indented fence body"],
  ["longer fence", "````\n```\n- [ ] still code\n````\n- [ ] out"],
  ["closing fence has no info string", "```js\n- [ ] a\n``` not a closer\n- [ ] b\n```\n- [ ] c"],
  ["backticks in the info string", "```npm install``` fixed the build\n- [ ] ship it"],
  ["backtick in a tilde info string", "~~~ info with ` backtick\n- [ ] in code\n~~~\n- [ ] out"],
  ["two backticks are not a fence", "``\n- [ ] a\n``"],
  ["fence closer with trailing blanks", "```\n- [ ] a\n```  \t\n- [ ] b"],
  ["frontmatter", "---\ntags: [a]\n- [ ] yaml\n---\n- [ ] body"],
  ["frontmatter closed by dots", "---\n- [ ] yaml\n...\n- [ ] body"],
  ["frontmatter with blanks", "--- \n- [ ] yaml\n---\t\n- [ ] body"],
  ["frontmatter must start on line 0", "\n---\n- [ ] not frontmatter\n---"],
  ["unclosed frontmatter", "---\n- [ ] one\n- [ ] two"],
  [
    "frontmatter closing at line 199",
    ["---", ...yaml199.slice(0, 198), "---", "- [ ] body"].join("\n"),
  ],
  ["frontmatter closing at line 200", ["---", ...yaml199, "---", "- [ ] body"].join("\n")],
  ["BOM before the first task", "\uFEFF- [ ] first"],
  ["BOM before frontmatter", "\uFEFF---\n- [ ] yaml\n---\n- [ ] body"],
  ["CRLF", "- [ ] one\r\n  - [x] two\r\n"],
  ["CRLF frontmatter", "---\r\na: b\r\n---\r\n- [ ] body\r\n"],
  ["lone CR lines", "- [ ] a\r\r\n- [ ] b\r"],
  [
    "nesting under plain bullets",
    [
      "- [ ] parent",
      "  - plain bullet",
      "    - [ ] grandchild under a plain bullet",
      "      deep note",
      "  1) numbered note",
      "- [ ] sibling",
      "lazy continuation at column 0",
    ].join("\n"),
  ],
  ["mixed tabs and spaces", "- [ ] a\n\t- [ ] b\n  \t- [ ] c\n    - [ ] d\n\t\t- note"],
  [
    "notes with markers and whitespace",
    "- [ ] a\n  -\u00a0nbsp marker\n  *\ttab\n  1.   spaced\n  + x",
  ],
  ["emoji offsets", "😀😀\n- [ ] 🎉 party\n  - [x] 👩‍💻 code review 🇫🇷"],
  ["CJK offsets", "日本語のメモ\n- [ ] 日本語のタスク\n  - 詳細"],
  ["combining marks", "- [ ] e\u0301cole\n- [ ] cafe\u0301 [[Cafe\u0301]]"],
  ["astral math letters", "𝒜 heading\n- [ ] 𝒷𝒸 task 𝒹"],
  ["nbsp starts the text", "- [ ]\u00a0nbsp start\u00a0"],
  ["nbsp before the marker", "\u00a0- [ ] nbsp indent"],
  ["nbsp-only line", "- [ ] a\n\u00a0\n  - note"],
  ["line-separator-only line", "- [ ] a\n\u2028\n  - note"],
  ["wikilinks in text", "- [ ] [[Link]] and ![[embed.png]] and [[Note#h|alias]] and [[ ]]"],
  ["pathological blanks", `- [ ]${" ".repeat(300)}x\u2028\n-${" \t".repeat(100)}\n- [ ] after`],
  [
    "deep nesting",
    Array.from({ length: 12 }, (_, i) => `${"  ".repeat(i)}- [ ] level ${i}`).join("\n"),
  ],
  ["dedent closes items", "- [ ] a\n    - [ ] b\n  - [ ] c\n- [ ] d"],
  ["paragraph between tasks", "- [ ] a\nparagraph\n  - [ ] b"],
];

// ── Generated documents (adapted from the core's tasks.property.test.ts) ────────────────────────

const indentArb = fc
  .array(fc.constantFrom(" ", "  ", "\t"), { maxLength: 3 })
  .map((p) => p.join(""));
const markerArb = fc.constantFrom("-", "*", "+", "1.", "2)", "10.", "10)", "123456789.");
const gapArb = fc.constantFrom(" ", "  ", "\t", " \t");
const statusArb = fc.constantFrom(
  " ",
  "x",
  "X",
  "/",
  "-",
  ">",
  "<",
  "?",
  "!",
  "*",
  "✓",
  "é",
  "$",
  "[",
  "]",
);
const wordArb = fc.constantFrom(
  "buy",
  "milk",
  "Call",
  "mom",
  "[[Daily/2026-09-24]]",
  "[[Note#Heading|alias]]",
  "![[img.png]]",
  "`code`",
  "#tag",
  "🎉",
  "👩‍💻",
  "🇫🇷",
  "𝒜",
  "שלום",
  "مرحبا",
  "日本語",
  "한국어",
  "café",
  "e\u0301",
  "[ ]",
  "[x]",
  "- [ ]",
  "...",
  "…",
  "--",
  "\t",
  "\u00a0",
  "\u2028",
  "a\rb",
  "$1",
  "$&",
  "a".repeat(60),
);
const textArb = fc.array(wordArb, { maxLength: 8 }).map((words) => words.join(" "));
const taskLineArb = fc
  .record({
    indent: indentArb,
    marker: markerArb,
    gap: gapArb,
    status: statusArb,
    rest: fc.option(fc.tuple(gapArb, textArb), { nil: undefined }),
  })
  .map(
    ({ indent, marker, gap, status, rest }) =>
      `${indent}${marker}${gap}[${status}]${rest ? rest[0] + rest[1] : ""}`,
  );
const otherLineArb = fc.oneof(
  fc.constantFrom(
    "",
    "   ",
    "\t",
    "## [ ] heading with a box",
    "> - [ ] quoted task",
    "| a | - [ ] | b |",
    "- [ ]foo",
    "-[ ] foo",
    "- [  ] foo",
    "- [🎉] astral status",
    "1234567890. [ ] ten digits",
    "***",
    "- - -",
    "``",
    "~~",
    "  continuation line",
    "\tindented note",
    "\u00a0",
  ),
  textArb.map((t) => `# ${t}`),
  textArb.map((t) => `- ${t}`),
  textArb.map((t) => `  - ${t}`),
  textArb,
);
const fenceArb = fc
  .record({
    char: fc.constantFrom("`", "~"),
    length: fc.integer({ min: 3, max: 5 }),
    indent: fc.constantFrom("", "  ", "\t"),
    info: fc.constantFrom("", "js", " ts title", " ~", "with spaces", " `x`"),
    body: fc.array(
      fc.oneof(taskLineArb, otherLineArb, fc.constantFrom("```js", "~~~~~~ trailing", "---")),
      {
        maxLength: 5,
      },
    ),
    extra: fc.integer({ min: -1, max: 2 }),
    trail: fc.constantFrom("", " ", "\t", " x"),
  })
  .map(({ char, length, indent, info, body, extra, trail }) => [
    `${indent}${char.repeat(length)}${info}`,
    ...body,
    `${indent}${char.repeat(length + extra)}${trail}`,
  ]);
const frontmatterArb = fc
  .record({
    open: fc.constantFrom("---", "---  ", "--- x"),
    yaml: fc.array(
      fc.oneof(taskLineArb, fc.constantFrom("tags: [daily]", "- item", "  - [ ] nested")),
      {
        maxLength: 4,
      },
    ),
    close: fc.constantFrom("---", "...", "--- ", "...\t", "----"),
  })
  .map(({ open, yaml, close }) => [open, ...yaml, close]);
const docArb = fc
  .record({
    bom: fc.boolean(),
    front: fc.option(frontmatterArb, { nil: undefined }),
    blocks: fc.array(
      fc.oneof(
        {
          weight: 3,
          arbitrary: fc.array(fc.oneof({ weight: 3, arbitrary: taskLineArb }, otherLineArb), {
            minLength: 1,
            maxLength: 8,
          }),
        },
        { weight: 1, arbitrary: fenceArb },
      ),
      { maxLength: 5 },
    ),
    crlf: fc.array(fc.boolean(), { minLength: 1, maxLength: 16 }),
    finalNewline: fc.boolean(),
  })
  .map(({ bom, front, blocks, crlf, finalNewline }) => {
    const lines = [...(front ?? []), ...blocks.flat()];
    let doc = bom ? "\uFEFF" : "";
    lines.forEach((line, i) => {
      doc += line;
      if (i < lines.length - 1 || finalNewline) doc += crlf[i % crlf.length] ? "\r\n" : "\n";
    });
    return doc;
  });

interface TaskVectors {
  about: string;
  documents: Array<{ name: string; doc: string; tasks: ParsedTask[] }>;
  lines: Array<{
    line: string;
    isTask: boolean;
    toggled: string;
    /** `[statusChar, setStatusCharOnLine(line, statusChar)]`. */
    setStatus: Array<[string, string]>;
  }>;
  /** `[text, isBlankTaskText(text)]`. */
  blank: Array<[string, boolean]>;
  /** `[char, statusFromChar(char)]`. */
  statusFromChar: Array<[string, TaskStatus]>;
  /** `[status, charFromStatus(status), isClosedStatus(status)]`. */
  statuses: Array<[TaskStatus, string, boolean]>;
}

export const RANDOM_DOCUMENT_COUNT = 220;

export function buildTaskVectors(core: CoreModule): TaskVectors {
  const random = sample(docArb, 7001, RANDOM_DOCUMENT_COUNT).map((doc, i): [string, string] => [
    `generated #${i + 1}`,
    doc,
  ]);
  const documents = [...CURATED, ...random]
    .filter(([, doc]) => isWellFormed(doc))
    .map(([name, doc]) => ({ name, doc, tasks: core.parseTasks(doc) }));

  const lineInputs = [
    "- [ ] a",
    "  - [x] a",
    "plain",
    "1. [ ] a",
    "- [/] started",
    "- [-] cancelled",
    "- [X] done",
    "- [ ]",
    "- [x]",
    "- []] odd",
    "- [ ]\tx",
    "- [ ] a\r",
    "- [🎉] astral",
    "- [\n] newline status",
    "- [ ] a\nb",
    "- [ ]\n",
    "",
    ...sample(fc.oneof(taskLineArb, otherLineArb), 7002, 80),
  ].filter(isWellFormed);
  const statusChars = [" ", "x", "/", "$", "$&", "$1", "🎉", ""];
  const lines = lineInputs.map((line) => ({
    line,
    isTask: core.isTaskLine(line),
    toggled: core.toggleTaskLine(line),
    setStatus: statusChars.map((ch): [string, string] => [ch, core.setStatusCharOnLine(line, ch)]),
  }));

  const blankInputs = [
    "",
    " … ",
    "Call mom",
    "🎉",
    "é",
    "猫",
    "ab",
    "a",
    "- - -",
    "..",
    "a.b",
    "\u00a0a\u00a0",
    "\u2028x\u2029",
    "a\u0301",
    ...sample(
      fc.array(fc.constantFrom(" ", "\t", ".", "…", "-", "\u00a0", "a", "猫", "🎉", "b"), {
        maxLength: 6,
      }),
      7003,
      30,
    ).map((parts) => parts.join("")),
  ];
  const chars = [" ", "x", "X", "/", "-", ">", "<", "?", "", "xx", "🎉", "\u2028"];
  const statuses: TaskStatus[] = ["open", "done", "in_progress", "cancelled", "deferred", "other"];
  return {
    about: ABOUT,
    documents,
    lines,
    blank: blankInputs.map((t) => [t, core.isBlankTaskText(t)]),
    statusFromChar: chars.map((c) => [c, core.statusFromChar(c)]),
    statuses: statuses.map((s) => [s, core.charFromStatus(s), core.isClosedStatus(s)]),
  };
}
