/** text.json: normalization, similarity, truncation, hashing and line splitting. */
import fc from "fast-check";
import { type CoreModule, isWellFormed, sample, uniqueBy } from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

/** Case mappings that differ between naive and JavaScript lowercasing, whitespace of every kind. */
const CURATED = [
  "",
  " ",
  "  Book  Dentist  ",
  "\tTabs\tand\nnewlines\r\n",
  "\u00a0nbsp\u00a0inside\u00a0",
  "\u2028line\u2029para\u2028",
  "\u3000ideographic\u3000space",
  "\u200bzero width is not space\u200b",
  "\ufeffbom\ufeff",
  "\u180emongolian\u180e",
  "ΟΔΟΣ",
  "ΟΔΟΣ ΟΔΟΣ",
  "Σ",
  "AΣ",
  "AΣB",
  "AΣ.",
  "A.Σ",
  "AΣ\u0301",
  "Α'Σ'",
  "ΣΑΣ",
  "İstanbul",
  "I\u0307",
  "\u212aelvin",
  "Straße ẞ",
  "ǅ ǈ ǋ",
  "ᎠᎡᎢ",
  "𐐀𐐁 Deseret",
  "ﬀ ﬁ",
  "ÀÉÎÕÜ",
  "Café e\u0301",
  "日本語 テキスト",
  "👩‍💻 CODE 🎉",
  "Ⅻ ⓐⒶ",
  "𝒜𝒷𝒸",
  "a\u0000b",
];

interface TextVectors {
  about: string;
  /** `[input, normalizeText(input)]`. */
  normalize: Array<[string, string]>;
  /** `[a, b, diceSimilarity(a, b)]`. */
  dice: Array<[string, string, number]>;
  /** `[a, b, minLength, isPrefixExtension(a, b, minLength)]`. */
  prefix: Array<[string, string, number, boolean]>;
  /** `[input, max, truncate(input, max)]`. */
  truncate: Array<[string, number, string]>;
  /** `[input, seed, hashString(input, seed)]`. */
  hash: Array<[string, number, string]>;
  /** `[input, splitLines(input)]`. */
  splitLines: Array<[string, string[]]>;
}

export function buildTextVectors(core: CoreModule): TextVectors {
  const textArb = fc.oneof(
    fc.string({ unit: "grapheme", maxLength: 30 }),
    fc.string({
      unit: fc.constantFrom("a", "b", "A", " ", "\t", "é", "🎉", "Σ", "İ"),
      maxLength: 12,
    }),
  );
  const texts = uniqueBy([...CURATED, ...sample(textArb, 5001, 120)], (t) => t).filter(
    isWellFormed,
  );

  const words = [
    "book",
    "dentist",
    "Book den",
    "book dentist appt",
    "water plants",
    "Bo",
    "call mom",
  ];
  const pairTexts = [
    ["book dentist", "Book  Dentist"],
    ["book dentist", "book the dentist"],
    ["book dentist", "water plants"],
    ["Email Sarah about the offsite agenda", "Email Sara about offsite agenda + budget"],
    ["a", "a"],
    ["a", "b"],
    ["ab", "ab "],
    ["aaaa", "aa"],
    ["ΟΔΟΣ", "οδος"],
    ["ΟΔΟΣ", "οδοσ"],
    ["İ", "i\u0307"],
    ["café", "cafe\u0301"],
    ["🎉🎉", "🎉"],
    ["", ""],
  ];
  const randomPairs = sample(fc.tuple(textArb, textArb), 5002, 80).filter(
    ([a, b]) => isWellFormed(a) && isWellFormed(b),
  );
  const pairs = [
    ...pairTexts,
    ...words.flatMap((a) => words.map((b) => [a, b])),
    ...randomPairs,
  ] as Array<[string, string]>;

  const prefix: TextVectors["prefix"] = [];
  pairs.forEach(([a, b], i) => {
    for (const min of [0, 3, i % 6]) prefix.push([a, b, min, core.isPrefixExtension(a, b, min)]);
  });

  const truncateTexts = [
    "short",
    "exactly ten",
    "a sentence that goes on",
    "trailing space here",
    "😀😀😀",
    "anything",
    "a😀b😀c😀d",
    "word\u00a0\u00a0\u00a0next",
    "日本語のテキストです",
    ...texts.slice(0, 40),
  ];
  const truncate: TextVectors["truncate"] = [];
  for (const text of truncateTexts) {
    for (const max of [-2, 0, 1, 2, 3, 4, 5, 10, 11, 20, 90])
      truncate.push([text, max, core.truncate(text, max)]);
  }

  const lineTexts = [
    "",
    "\n",
    "a\nb",
    "a\r\nb\r\n",
    "a\rb",
    "a\r\r\nb",
    "\r\n\r\n",
    "one\ntwo\r\nthree\n",
    "\u2028not a break",
  ];

  return {
    about: ABOUT,
    normalize: texts.map((t) => [t, core.normalizeText(t)]),
    dice: pairs.map(([a, b]) => [a, b, core.diceSimilarity(a, b)]),
    prefix,
    truncate,
    hash: [...texts.slice(0, 60), "- [ ] task 1", "\uD83D\uDE00"].flatMap((t, i) => [
      [t, 0, core.hashString(t)],
      [t, i * 7919, core.hashString(t, i * 7919)],
    ]) as TextVectors["hash"],
    splitLines: lineTexts.map((t) => [t, core.splitLines(t)]),
  };
}
