/** tracker.json and anchors.json: task identity across edits, and anchor re-resolution. */
import fc from "fast-check";
import type { TaskDiff, TrackedTask } from "../../../../packages/core/src/index.ts";
import { type CoreModule, sample } from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

/** `[id, text, status, line, depth, parentId, notes, firstSeenAt, updatedAt]`. */
type TaskRow = [string, string, string, number, number, string | null, string[], number, number];

interface Step {
  doc: string;
  now: number;
  /** Full rows; large sequences only record `ids` (the other fields come from the parser). */
  tasks?: TaskRow[];
  ids?: string[];
  diff: {
    added: string[];
    /** `[id, changes]`. */
    updated: Array<[string, string[]]>;
    statusChanged: string[];
    removed: string[];
  };
}

interface TrackerVectors {
  about: string;
  /** Each sequence starts from no tasks; ids come from a counter `t1, t2, …` shared by its steps. */
  sequences: Array<{ name: string; similarityThreshold: number | null; steps: Step[] }>;
}

const row = (t: TrackedTask): TaskRow => [
  t.id,
  t.text,
  t.status,
  t.line,
  t.depth,
  t.parentId,
  t.notes,
  t.firstSeenAt,
  t.updatedAt,
];

const diffRow = (diff: TaskDiff): Step["diff"] => ({
  added: diff.added.map((t) => t.id),
  updated: diff.updated.map((u) => [u.task.id, u.changes]),
  statusChanged: diff.statusChanged.map((s) => s.task.id),
  removed: diff.removed.map((t) => t.id),
});

function runSequence(
  core: CoreModule,
  name: string,
  docs: readonly string[],
  similarityThreshold?: number,
): TrackerVectors["sequences"][number] {
  let n = 0;
  const idFactory = () => `t${++n}`;
  let state: TrackedTask[] = [];
  const steps = docs.map((doc, i): Step => {
    const now = 1_000 * (i + 1);
    const { tasks, diff } = core.trackTasks(state, core.parseTasks(doc), {
      idFactory,
      now,
      ...(similarityThreshold === undefined ? {} : { similarityThreshold }),
    });
    state = tasks;
    const large = tasks.length > 120;
    return large
      ? { doc, now, ids: tasks.map((t) => t.id), diff: diffRow(diff) }
      : { doc, now, tasks: tasks.map(row), diff: diffRow(diff) };
  });
  return { name, similarityThreshold: similarityThreshold ?? null, steps };
}

// ── Targeted cases: each pins one constant or tie-break of the matcher ─────────────────────────

/** Deterministic letter salad: texts that share (almost) no bigrams with each other. */
function salad(seed: number, words = 3): string {
  let s = (seed * 2_654_435_761 + 12_345) >>> 0;
  const out: string[] = [];
  for (let w = 0; w < words; w++) {
    let word = "";
    for (let i = 0; i < 6; i++) {
      s = (Math.imul(s, 1_103_515_245) + 12_345) >>> 0;
      word += String.fromCharCode(97 + ((s >>> 16) % 26));
    }
    out.push(word);
  }
  return out.join(" ");
}

const doc = (texts: readonly string[]) =>
  texts.map((t) => (t === "" ? "" : `- [ ] ${t}`)).join("\n");

/**
 * One new task `target` (at `line`) competing for two removed tasks: `a` at `line - da` and `b` at
 * `line - db`. Every other line is an unchanged filler, so no anchor shifts anything.
 */
function competition(target: string, a: string, da: number, b: string, db: number): string[] {
  const size = Math.max(da, db) + 4;
  const line = size - 2;
  const previous = Array.from({ length: size }, (_, i) => salad(9_000 + i));
  const next = [...previous];
  previous[line - da] = a;
  previous[line - db] = b;
  next[line - da] = salad(9_500 + da);
  next[line - db] = salad(9_600 + db);
  next[line] = target;
  return [doc(previous), doc(next)];
}

function targetedSequences(core: CoreModule): Array<[string, string[], number?]> {
  const out: Array<[string, string[], number?]> = [];
  const target = "buy milk and eggs today";
  const typedFrom = "buy milk and eggs";
  const rivals = [
    "buy milk and bread today",
    "buy oat milk and eggs",
    "buy milk and eggs tomorrow",
    "buy almond milk today",
    "milk and eggs today",
  ];
  const words = target.split(" ");
  const swaps = ["oat", "bread", "tea", "soon", "now", "cheese", "fresh", "some"];
  const swapped = words.flatMap((_, i) => swaps.map((s) => words.map((w, j) => (j === i ? s : w))));
  const variants = [
    ...rivals,
    ...words.map((_, i) => words.filter((__, j) => j !== i).join(" ")),
    ...swapped.map((w) => w.join(" ")),
    ...words.flatMap((_, i) =>
      swaps.map((s) => [...words.slice(0, i), s, ...words.slice(i)].join(" ")),
    ),
    ...swapped.flatMap((w) => w.map((_, i) => w.filter((__, j) => j !== i).join(" "))),
  ].filter((v) => !core.isPrefixExtension(target, v));
  const typed = Math.max(0.9, core.diceSimilarity(target, typedFrom));
  const gap = (rival: string) => typed - core.diceSimilarity(target, rival);
  // Near ties decided by the line-distance weight (0.01 per line) …
  for (const rival of rivals) {
    const lines = Math.round(gap(rival) / 0.015);
    if (lines >= 1 && lines <= 19) {
      out.push([
        `distance weight decides: ${rival}`,
        competition(target, typedFrom, lines + 1, rival, 1),
      ]);
    }
  }
  // … and by its cap (20 lines): 30 lines away costs 0.2, neither 0.3 nor 0.15.
  const capped = variants.find((v) => gap(v) > 0.155 && gap(v) < 0.195);
  if (capped)
    out.push([`distance cap decides: ${capped}`, competition(target, typedFrom, 30, capped, 0)]);
  const beyond = variants.find((v) => gap(v) > 0.205 && gap(v) < 0.29);
  if (beyond)
    out.push([
      `distance cap still counts: ${beyond}`,
      competition(target, typedFrom, 30, beyond, 0),
    ]);
  // Still typing counts as 0.9, whatever Dice says.
  out.push([
    "prefix extension scores 0.9",
    ["- [ ] Book den", "- [ ] Book dentist appointment for Tuesday"],
    0.88,
  ]);
  // Equal scores: the first pair considered (earlier parsed task) wins.
  out.push([
    "equal scores keep document order",
    [
      doc([salad(1), salad(2), salad(3), salad(4), salad(5), "fix bike", salad(6), salad(7)]),
      doc([salad(1), salad(2), salad(3), salad(4), "fix bikes", salad(8), "fix biker", salad(7)]),
    ],
  ]);
  // Duplicate alignment ties keep the earlier task (both copies are one line from the original).
  out.push([
    "duplicate alignment ties keep the earlier task",
    [
      doc([salad(11), salad(12), salad(13), salad(14), salad(15), "call", salad(16)]),
      doc([salad(11), salad(12), salad(13), salad(14), "call", salad(17), "call", salad(16)]),
    ],
  ]);
  // Expected lines come from the nearest anchor above (shifted by 5 inserted lines here).
  const above = Array.from({ length: 30 }, (_, i) => salad(200 + i));
  const beforeShift = [...above];
  beforeShift[20] = "same";
  beforeShift[25] = "same";
  const afterShift = [
    ...above.slice(0, 15),
    ...[1, 2, 3, 4, 5].map((i) => salad(300 + i)),
    ...above.slice(15, 20),
    "same",
    ...above.slice(21, 25),
    ...above.slice(26),
  ];
  out.push(["expected lines use the anchor above", [doc(beforeShift), doc(afterShift)]]);
  // 190 × 190 open pairs fit the fuzzy budget (40k): a task moved far away is still found.
  const moved = Array.from({ length: 190 }, (_, i) => salad(1_000 + i));
  const rewritten = moved.map((t) => `${t} ok`);
  out.push([
    "fuzzy pass compares everything within its budget",
    [doc(moved), doc([rewritten.at(-1)!, ...rewritten.slice(0, -1)])],
  ]);
  // 1010 open tasks: the window shrinks to its minimum, 20 lines; a task moved 20 lines is found.
  const many = Array.from({ length: 1010 }, (_, i) => salad(5_000 + i));
  const manyRewritten = many.map((t) => `${t} ok`);
  const shuffled = [...manyRewritten];
  const [picked] = shuffled.splice(500, 1);
  shuffled.splice(520, 0, picked!);
  const [raised] = shuffled.splice(700, 1);
  shuffled.splice(680, 0, raised!);
  out.push(["windowed fuzzy pass keeps its minimum window", [doc(many), doc(shuffled)]]);
  // 500 × 450 duplicates fit the alignment budget (250k): the optimal, order-preserving alignment
  // (a greedy one would cross the pair at lines 10/11 over to lines 11/5).
  const size = 600;
  const fillers = Array.from({ length: size }, (_, i) => salad(20_000 + i));
  const before = [...fillers];
  const after = [...fillers];
  for (const line of [10, 11]) before[line] = "same";
  for (const line of [5, 11, 50]) after[line] = "same";
  for (let k = 0; k < 448; k++) before[100 + k] = "same";
  for (let k = 0; k < 497; k++) after[100 + k] = "same";
  out.push(["duplicate alignment is optimal within its budget", [doc(before), doc(after)]]);
  return out;
}

const lines = (...items: string[]) => items.join("\n");

function typing(target: string, before: string[], after: string[]): string[] {
  const docs = [lines(...before, ...after)];
  for (let length = 1; length <= target.length; length++) {
    docs.push(lines(...before, `- [ ] ${target.slice(0, length)}`, ...after));
  }
  return docs;
}

const note = (count: number, label: (i: number) => string) =>
  Array.from({ length: count }, (_, i) => `- [ ] ${label(i)}`).join("\n");

function curatedSequences(): Array<[string, string[], number?]> {
  return [
    ["new tasks get ids", ["- [ ] a task\n- [ ] another task"]],
    [
      "prefix extension while typing",
      ["- [ ] Book den", "- [ ] Book dentist appointment for Tuesday"],
    ],
    [
      "typo fixes and small rewrites",
      [
        "- [ ] Email Sarah about the offsite agenda",
        "- [ ] Email Sara about offsite agenda + budget",
      ],
    ],
    [
      "reorder",
      [
        "- [ ] alpha task\n- [ ] beta task\n- [ ] gamma task",
        "- [ ] gamma task\n- [ ] alpha task\n- [ ] beta task",
      ],
    ],
    [
      "status change only",
      ["- [ ] pay rent", "- [x] pay rent", "- [/] pay rent", "- [-] pay rent"],
    ],
    [
      "removal and a genuinely new task",
      [
        "- [ ] buy milk\n- [ ] renew car registration",
        "- [ ] renew car registration\n- [ ] plan birthday party",
      ],
    ],
    [
      "duplicates by line proximity",
      [
        "- [ ] call\n- [ ] x y z\n- [ ] call",
        "- [ ] new first\n- [ ] call\n- [ ] x y z\n- [ ] call",
      ],
    ],
    [
      "notes change",
      ["- [ ] plan trip", "- [ ] plan trip\n  - budget $2k", "- [ ] plan trip\n  - budget $3k"],
    ],
    [
      "nested parent ids",
      ["- [ ] parent task\n  - [ ] child task", "- [ ] parent task\n- [ ] child task"],
    ],
    [
      "typing a duplicate above an existing task",
      [
        "- [ ] call mom",
        ...["c", "ca", "cal", "call mo", "call mom"].map((p) => `- [ ] ${p}\n- [ ] call mom`),
      ],
    ],
    [
      "deleting one of two duplicates",
      ["- [ ] call\n- [ ] x marks the spot\n- [ ] call", "- [ ] x marks the spot\n- [ ] call"],
    ],
    [
      "inserting above a run of duplicates",
      ["- [ ] call\n- [ ] call", "- [ ] brand new\n- [ ] call\n- [ ] call"],
    ],
    [
      "duplicates matched by position, not checkbox",
      ["- [x] call\n- [ ] call", "- [ ] call\n- [x] call"],
    ],
    [
      "typing a task character by character",
      typing(
        "Call the plumber about the leak",
        ["- [ ] water plants", "- [x] renew passport"],
        ["- [ ] pay rent"],
      ),
    ],
    [
      "typing a copy of an existing task",
      typing("pay rent", ["- [ ] pay rent"], ["- [ ] fix bike"]),
    ],
    [
      "backspacing to empty and retyping",
      [
        "- [ ] fix bike\n- [ ] review pr",
        "- [ ] fix bik\n- [ ] review pr",
        "- [ ] fi\n- [ ] review pr",
        "- [ ] \n- [ ] review pr",
        "- [ ] f\n- [ ] review pr",
        "- [ ] fix the car\n- [ ] review pr",
      ],
    ],
    [
      "moving a block",
      [
        lines("- [ ] one", "- [ ] two", "- [ ] three", "- [ ] four", "- [ ] five", "- [ ] six"),
        lines("- [ ] four", "- [ ] five", "- [ ] six", "- [ ] one", "- [ ] two", "- [ ] three"),
      ],
    ],
    [
      "in-place rewrites",
      [
        lines("- [ ] fix bike", "- [ ] call dentist", "- [ ] water the plants"),
        lines("- [ ] fix the car", "- [ ] call the vet", "- [ ] plants"),
        lines("- [ ] completely different", "- [ ] call the vet", "- [ ] xyz"),
      ],
    ],
    [
      "mass rewrite uses the windowed fuzzy pass",
      [
        note(210, (i) => `follow up with vendor ${i} about invoice ${i * 7}`),
        note(210, (i) => `follow up with the vendor ${i} about invoice #${i * 7}!`),
      ],
    ],
    [
      "large duplicate group uses greedy alignment",
      [
        note(500, () => "same text"),
        `${note(10, () => "same text")}\n${note(500, () => "same text")}`,
      ],
    ],
    [
      "large duplicate group with a deletion",
      [note(300, () => "same text"), note(299, () => "same text")],
    ],
    ["lower similarity threshold", ["- [ ] fix bike", "- [ ] fix the car"], 0.3],
    [
      "higher similarity threshold",
      ["- [ ] Email Sarah about the offsite", "- [ ] Email Sara about offsite"],
      0.8,
    ],
    [
      "CRLF, BOM and frontmatter",
      [
        "\uFEFF---\r\ntags: [x]\r\n---\r\n- [ ] one\r\n- [ ] two\r\n",
        "---\ntags: [x]\n---\n- [ ] two\n- [x] one\n",
      ],
    ],
    [
      "notes and nesting toggles",
      [
        lines("- [ ] a task", "- [ ] b task", "  - detail"),
        lines("- [ ] a task", "  - [ ] b task", "    - detail"),
        lines("- [ ] a task", "  - [ ] b task", "    - detail", "    - more"),
      ],
    ],
    [
      "unicode case folding and normalization",
      [
        lines("- [ ] ΟΔΟΣ plan", "- [ ] İstanbul trip", "- [ ] café"),
        lines("- [ ] οδος plan", "- [ ] istanbul trip", "- [ ] cafe\u0301"),
        lines("- [ ] ΟΔΟΣ PLAN", "- [ ] i\u0307stanbul trip", "- [ ] café"),
      ],
    ],
    [
      "blank template tasks",
      ["- [ ] ", "- [ ] \n- [ ] ", "- [ ] b\n- [ ] ", "- [ ] buy\n- [ ] … "],
    ],
  ];
}

// ── Random edit sequences (adapted from the core's task-tracker.property.test.ts) ─────────────

interface Item {
  text: string;
  status: " " | "x" | "/";
  nested: boolean;
  notes: string[];
}

function render(items: readonly Item[]): string {
  const out: string[] = [];
  items.forEach((item, i) => {
    const indent = item.nested && i > 0 ? "  " : "";
    out.push(`${indent}- [${item.status}] ${item.text}`);
    for (const n of item.notes) out.push(`${indent}  - ${n}`);
  });
  return out.join("\n");
}

const WORDS =
  "call mom buy milk book dentist email sarah plan trip renew passport pay rent water plants fix bike review pr".split(
    " ",
  );
const wordsArb = fc
  .array(fc.constantFrom(...WORDS), { minLength: 1, maxLength: 4 })
  .map((w) => w.join(" "));
const itemArb: fc.Arbitrary<Item> = fc.record({
  text: wordsArb,
  status: fc.constantFrom<Item["status"]>(" ", "x", "/"),
  nested: fc.boolean(),
  notes: fc.array(fc.constantFrom("budget $2k", "ask Sam", "before Friday"), { maxLength: 1 }),
});

type Edit =
  | { kind: "insert"; at: number; item: Item }
  | { kind: "delete" | "backspace" | "toggle" | "note" | "nest"; at: number }
  | { kind: "retext"; at: number; text: string }
  | { kind: "type"; at: number; suffix: string }
  | { kind: "move"; from: number; to: number };

const editArb: fc.Arbitrary<Edit> = fc.oneof(
  fc.record({ kind: fc.constant("insert" as const), at: fc.nat(), item: itemArb }),
  fc.record({
    kind: fc.constantFrom("delete", "backspace", "toggle", "note", "nest"),
    at: fc.nat(),
  }),
  fc.record({ kind: fc.constant("retext" as const), at: fc.nat(), text: wordsArb }),
  fc.record({
    kind: fc.constant("type" as const),
    at: fc.nat(),
    suffix: fc.constantFrom(" ", "s", " today", "!", " [[Daily/2026-09-24]]"),
  }),
  fc.record({ kind: fc.constant("move" as const), from: fc.nat(), to: fc.nat() }),
);

function applyEdit(items: readonly Item[], edit: Edit): Item[] {
  const next = items.map((item) => ({ ...item, notes: [...item.notes] }));
  if (edit.kind === "insert") {
    next.splice(edit.at % (next.length + 1), 0, edit.item);
    return next;
  }
  if (next.length === 0) return next;
  if (edit.kind === "move") {
    const [moved] = next.splice(edit.from % next.length, 1);
    next.splice(edit.to % (next.length + 1), 0, moved!);
    return next;
  }
  const item = next[edit.at % next.length]!;
  switch (edit.kind) {
    case "delete":
      next.splice(edit.at % next.length, 1);
      break;
    case "retext":
      item.text = edit.text;
      break;
    case "type":
      item.text += edit.suffix;
      break;
    case "backspace":
      item.text = item.text.slice(0, -1);
      break;
    case "toggle":
      item.status = item.status === "x" ? " " : "x";
      break;
    case "note":
      item.notes.push("follow-up");
      break;
    case "nest":
      item.nested = !item.nested;
      break;
  }
  return next;
}

const scenarioArb = fc.tuple(
  fc.array(itemArb, { minLength: 1, maxLength: 8 }),
  fc.array(fc.array(editArb, { minLength: 1, maxLength: 3 }), { minLength: 1, maxLength: 6 }),
);

export function buildTrackerVectors(core: CoreModule): TrackerVectors {
  const sequences = [...curatedSequences(), ...targetedSequences(core)].map(
    ([name, docs, threshold]) => runSequence(core, name, docs, threshold),
  );
  sample(scenarioArb, 8001, 45).forEach(([initial, batches], i) => {
    let items = initial;
    const docs = [render(items)];
    for (const batch of batches) {
      for (const edit of batch) items = applyEdit(items, edit);
      docs.push(render(items));
    }
    sequences.push(runSequence(core, `random edits #${i + 1}`, docs));
  });
  return { about: ABOUT, sequences };
}

interface AnchorVectors {
  about: string;
  cases: Array<{
    name: string;
    doc: string;
    /** `[taskId, text, line]`. */
    anchors: Array<[string, string, number]>;
    /** `resolveTaskAnchors(doc, anchors)` as an object. */
    resolved: Record<string, number>;
  }>;
}

export function buildAnchorVectors(core: CoreModule): AnchorVectors {
  const cases: AnchorVectors["cases"] = [];
  const add = (name: string, doc: string, anchors: Array<[string, string, number]>) => {
    const map = core.resolveTaskAnchors(
      doc,
      anchors.map(([taskId, text, line]) => ({ taskId, text, line })),
    );
    cases.push({ name, doc, anchors, resolved: Object.fromEntries(map) });
  };
  add(
    "anchors follow local edits",
    "- [ ] New task on top\n- [ ] Book dentist for Tuesday\n\n- [ ] Renew passport",
    [
      ["a", "Book dentist", 0],
      ["b", "Renew passport", 1],
    ],
  );
  add("deleted task drops its anchor", "- [ ] something else entirely", [["a", "Book dentist", 0]]);
  add("empty task id is never reported", "- [ ] one\n- [ ] two", [
    ["", "one", 0],
    ["b", "two", 1],
  ]);
  add("duplicate anchor ids", "- [ ] one\n- [ ] two", [
    ["a", "one", 0],
    ["a", "two", 1],
  ]);
  add("anchors sharing a line", "- [ ] alpha\n- [ ] beta", [
    ["a", "alpha", 0],
    ["b", "alpha beta", 0],
    ["c", "gamma", 1],
  ]);
  add("duplicate texts", "- [ ] call\n- [ ] new\n- [ ] call\n- [ ] call", [
    ["a", "call", 0],
    ["b", "call", 1],
  ]);
  add("no tasks", "just prose", [["a", "anything", 0]]);
  add("no anchors", "- [ ] one", []);
  const big = Array.from(
    { length: 400 },
    (_, i) => `- [ ] Task number ${i}: follow up with vendor ${i % 17}`,
  );
  add(
    "fifty anchors in a long note",
    big.join("\n").replace("Task number 5:", "Task number 5 (edited):"),
    Array.from({ length: 50 }, (_, i): [string, string, number] => [`a${i}`, big[i]!.slice(6), i]),
  );

  const randomArb = fc.tuple(
    fc.array(itemArb, { minLength: 1, maxLength: 10 }),
    fc.array(editArb, { maxLength: 6 }),
    fc.array(fc.boolean(), { minLength: 12, maxLength: 12 }),
  );
  sample(randomArb, 9001, 80).forEach(([initial, edits, keep], i) => {
    let n = 0;
    const state = core.trackTasks([], core.parseTasks(render(initial)), {
      idFactory: () => `t${++n}`,
      now: 1,
    }).tasks;
    const doc = render(edits.reduce(applyEdit, initial));
    const anchors = state
      .filter((_, j) => keep[j % keep.length])
      .map((t): [string, string, number] => [t.id, t.text, t.line]);
    add(`random #${i + 1}`, doc, anchors);
  });
  return { about: ABOUT, cases };
}
