/** wikilinks.json: parsing `[[target#subpath|alias]]` and resolving targets against vault paths. */
import fc from "fast-check";
import { type CoreModule, isWellFormed, sample, uniqueBy } from "./common";

const ABOUT = "Generated by apps/macos/scripts/generate-vectors.ts from @ddl/core. Do not edit.";

const CURATED_TEXTS = [
  "[[Daily/2026-09-24]]",
  "[[Note#Heading]]",
  "[[Note#^block-id]]",
  "[[Note#A#B|shown]]",
  "[[Note|a|b]]",
  "![[photo.png|300]]",
  "[[ spaced  ]]",
  "[[a[b]]]",
  "[[日記/2026年]]",
  "[[]]",
  "[[ ]]",
  "[[#Heading only]]",
  "[[|alias only]]",
  "[[unclosed",
  "[[multi\nline]]",
  "[[a#]]",
  "[[a# ]]",
  "[[a| ]]",
  "[[a#b| ]]",
  "[[a]]]]",
  "!![[x]]",
  "[[[a]]]",
  "[[[[a]]]]",
  "[[a]]b[[c]]",
  "😀[[日記]] and ![[e\u0301]]",
  "Move to [[Daily/2026-09-24]] and [[Projects/Plan|the plan]]",
  "[[a\\b]] [[/root]] [[x.png]]",
  "[[a]b]]",
  "[[a|b]c]]",
  "[[a#b]c]]",
  "[[a|b\nc]]",
  "[[a#b\nc]]",
  "text ]] [[ text",
  "![[",
  "[[\u2028]]",
  "[[\ttab\t]]",
];

interface WikiLinkVectors {
  about: string;
  parse: Array<{
    text: string;
    links: Array<{
      target: string;
      subpath: string | null;
      alias: string | null;
      embed: boolean;
      from: number;
      to: number;
    }>;
  }>;
  resolve: Array<{ target: string; paths: string[]; result: string | null }>;
}

const partChar = (forbidden: string) =>
  fc
    .oneof(
      fc.constantFrom(...[..."aBz09 -_./(é日🎉[^!|#"], "\u0301"),
      fc.string({ unit: "grapheme", minLength: 1, maxLength: 1 }),
    )
    .filter((ch) => ![...forbidden].some((f) => ch.includes(f)));
const partArb = (forbidden: string, minLength = 1) =>
  fc.array(partChar(forbidden), { minLength, maxLength: 10 }).map((chars) => chars.join(""));
const linkArb = fc
  .record({
    embed: fc.boolean(),
    target: partArb("]|#\n"),
    subpath: fc.option(partArb("]|\n"), { nil: undefined }),
    alias: fc.option(partArb("]\n"), { nil: undefined }),
  })
  .map(
    (p) =>
      `${p.embed ? "!" : ""}[[${p.target}${p.subpath === undefined ? "" : `#${p.subpath}`}${p.alias === undefined ? "" : `|${p.alias}`}]]`,
  );
const proseArb = partArb("\n", 0);

export function buildWikiLinkVectors(core: CoreModule): WikiLinkVectors {
  const random = sample(fc.array(fc.tuple(proseArb, linkArb), { maxLength: 4 }), 6001, 150).map(
    (pieces) => pieces.map(([prose, link]) => `${prose}${link}`).join(" "),
  );
  const texts = uniqueBy([...CURATED_TEXTS, ...random], (t) => t).filter(isWellFormed);
  const parse = texts.map((text) => ({
    text,
    links: core.parseWikiLinks(text).map((l) => ({
      target: l.target,
      subpath: l.subpath ?? null,
      alias: l.alias ?? null,
      embed: l.embed,
      from: l.from,
      to: l.to,
    })),
  }));

  const pathArb = fc
    .tuple(
      fc.constantFrom("", "Daily/", "Archive/", "Projects/Work/", "archive/Old/", "Daily/Archive/"),
      fc.constantFrom(
        "Plan",
        "plan",
        "2026-09-24",
        "v1.2 notes",
        "v1",
        "image",
        "Meeting 2026.09.23",
        "日記",
        "Cafe\u0301",
        "ΟΔΟΣ",
      ),
      fc.constantFrom(".md", ".MD", ".png", ".md.bak", ""),
    )
    .map(([folder, name, ext]) => `${folder}${name}${ext}`);
  const targetArb = fc
    .tuple(
      fc.constantFrom("", "Daily/", "Archive/", "Work/", "/", "archive/old/", "\\"),
      fc.constantFrom(
        "Plan",
        "PLAN",
        "2026-09-24",
        "v1.2 notes",
        "v1",
        "image.png",
        "Meeting 2026.09.23",
        "日記",
        "Plan.md",
        "Café",
        "οδος",
        "",
      ),
    )
    .map(([folder, name]) => `${folder}${name}`);
  const curated: Array<[string, string[]]> = [
    ["Daily/2026-09-24", ["Archive/Daily/2026-09-24.md", "Daily/2026-09-24.md", "2026-09-24.md"]],
    ["2026-09-24", ["Archive/Daily/2026-09-24.md", "Daily/2026-09-24.md", "2026-09-24.md"]],
    ["daily/2026-09-24", ["Archive/Daily/2026-09-24.md"]],
    ["Caf\u00e9", ["Notes/Cafe\u0301.md"]],
    ["Cafe\u0301/Menu", ["Caf\u00e9/Menu.md"]],
    ["Projects/Plan", ["Archive/Plan.md"]],
    ["v1.2 notes", ["v1.md"]],
    ["v1.2 notes", ["Archive/v1.2 notes.md", "v1.md"]],
    ["image.png", ["image.md", "Attachments/image.png"]],
    ["Plan", ["b/Plan.md", "a/Plan.md", "Plans.md"]],
    ["", ["Plan.md"]],
    ["/", ["Plan.md"]],
    ["\\Plan", ["Plan.md"]],
    ["//Plan", ["Plan.md", "x//Plan.md"]],
    ["ΟΔΟΣ", ["οδος.md"]],
    ["ΟΔΟΣ", ["οδοσ.md"]],
  ];
  const resolveCases: Array<[string, string[]]> = [
    ...curated,
    ...sample(fc.tuple(targetArb, fc.uniqueArray(pathArb, { maxLength: 12 })), 6002, 150),
  ];
  return {
    about: ABOUT,
    parse,
    resolve: resolveCases.map(([target, paths]) => ({
      target,
      paths,
      result: core.resolveWikiLink(target, paths),
    })),
  };
}
