/**
 * Offline stand-ins for the agent's "hands", built so the REAL tool code runs on top of them:
 * a web transport for `createWebTools` (web_fetch/web_search), a browser controller for the real
 * `browser_*` tools, an execution provider, and MCP connectors made with the real
 * `createMcpToolSpec`. Irreversible effects (orders placed, emails sent…) are recorded so tests can
 * prove they only happen after approval.
 */
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import {
  type ConnectorToolSource,
  createMcpToolSpec,
  type McpToolDefinition,
} from "@ddl/connectors";
import type { ConnectorStatus, ToolSpec, Unsubscribe } from "@ddl/core";
import type {
  BrowserController,
  BrowserSession,
  BrowserSnapshot,
  BrowserTarget,
  ExecutionProvider,
  FrameListener,
  ShellExecOptions,
  ShellResult,
  Workspace,
} from "../execution/types";
import type { LlmClient } from "../llm/types";
import { createWebTools, type LookupAddresses } from "../tools/web";

// ── Web ─────────────────────────────────────────────────────────────────────

export interface FakePage {
  status?: number;
  contentType?: string;
  body: string;
}

export interface FakeWeb {
  /** Replaces the network for `web_fetch`. */
  fetch: typeof fetch;
  /** Resolves every host to a public address, so the SSRF checks pass without DNS. */
  lookup: LookupAddresses;
  /** URLs fetched, in order. */
  readonly fetched: string[];
}

/** Pages keyed by URL (exact, or origin + path); anything else gets a generated article. */
export function createFakeWeb(pages: Record<string, FakePage> = {}): FakeWeb {
  const fetched: string[] = [];
  const fakeFetch = (async (input: string | URL | Request) => {
    const url = typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
    fetched.push(url);
    const parsed = new URL(url);
    const page = pages[url] ?? pages[`${parsed.origin}${parsed.pathname}`] ?? defaultPage(parsed);
    return new Response(page.body, {
      status: page.status ?? 200,
      headers: { "content-type": page.contentType ?? "text/html; charset=utf-8" },
    });
  }) as typeof fetch;
  return {
    fetch: fakeFetch,
    lookup: async () => [{ address: "93.184.216.34", family: 4 }],
    fetched,
  };
}

/** The real web tools (web_fetch + web_search) on a fake network and the given LLM client. */
export function createFakeWebTools(options: { llm?: LlmClient; web?: FakeWeb } = {}): ToolSpec[] {
  const web = options.web ?? createFakeWeb();
  return createWebTools({
    ...(options.llm ? { llm: options.llm } : {}),
    fetch: web.fetch,
    lookup: web.lookup,
  });
}

function defaultPage(url: URL): FakePage {
  const topic = decodeURIComponent(
    url.pathname.split("/").filter(Boolean).at(-1) ?? "home",
  ).replace(/[-_]+/g, " ");
  const body = `<!doctype html><html><head><title>${escapeHtml(topic)} — ${url.hostname}</title></head><body><main>
<h1>${escapeHtml(topic)}</h1>
<p>This page on ${url.hostname} is generated by the fake web. It compares a few options for ${escapeHtml(topic)} so the agent has something realistic to read, summarize and cite.</p>
<ul><li>Option A — the best all-rounder, mid-priced.</li><li>Option B — the budget pick.</li><li>Option C — the fastest, but pricey.</li></ul>
<p>Prices and availability are illustrative only; nothing here is real.</p>
</main></body></html>`;
  return { body };
}

// ── Browser ─────────────────────────────────────────────────────────────────

export interface BrowserEffect {
  threadKey: string;
  /** "Place order", "Confirm booking", "Pay now", "Send"… */
  action: string;
  url: string;
}

export interface FakeBrowser extends BrowserController {
  /** Every browser action, e.g. `navigate https://…`, `click Place order`. */
  readonly actions: string[];
  /** Irreversible clicks that went through. */
  readonly effects: BrowserEffect[];
}

const IRREVERSIBLE_BUTTON = /place order|confirm booking|pay now|send|buy now|checkout/i;

export function createFakeBrowser(): FakeBrowser {
  const sessions = new Map<string, FakeBrowserSession>();
  const actions: string[] = [];
  const effects: BrowserEffect[] = [];
  return {
    actions,
    effects,
    async session(key) {
      let session = sessions.get(key);
      if (!session) {
        session = new FakeBrowserSession(key, actions, effects);
        sessions.set(key, session);
      }
      return session;
    },
    has: (key) => sessions.has(key),
    async close(key) {
      sessions.delete(key);
    },
    async dispose() {
      sessions.clear();
    },
  };
}

const ELEMENTS = [
  { role: "textbox", name: "Search" },
  { role: "button", name: "Search" },
  { role: "link", name: "Option A — best all-rounder" },
  { role: "button", name: "Add to cart" },
  { role: "button", name: "Place order" },
  { role: "button", name: "Confirm booking" },
  { role: "button", name: "Pay now" },
];

class FakeBrowserSession implements BrowserSession {
  readonly key: string;
  private url = "about:blank";
  private status = "";
  private readonly listeners = new Set<FrameListener>();
  private readonly actions: string[];
  private readonly effects: BrowserEffect[];

  constructor(key: string, actions: string[], effects: BrowserEffect[]) {
    this.key = key;
    this.actions = actions;
    this.effects = effects;
  }

  async navigate(url: string): Promise<BrowserSnapshot> {
    this.url = url;
    this.status = "";
    return this.act(`navigate ${url}`);
  }

  async snapshot(): Promise<BrowserSnapshot> {
    return this.render();
  }

  async click(target: BrowserTarget): Promise<BrowserSnapshot> {
    const name = this.resolve(target);
    if (IRREVERSIBLE_BUTTON.test(name)) {
      this.effects.push({ threadKey: this.key, action: name, url: this.url });
      this.status = `${name} — done. (Fake page: nothing real happened.)`;
    }
    return this.act(`click ${name}`);
  }

  async type(
    target: BrowserTarget,
    text: string,
    options?: { submit?: boolean },
  ): Promise<BrowserSnapshot> {
    return this.act(
      `type ${this.resolve(target)} ${JSON.stringify(text)}${options?.submit ? " +enter" : ""}`,
    );
  }

  async selectOption(target: BrowserTarget, values: string[]): Promise<BrowserSnapshot> {
    return this.act(`select ${this.resolve(target)} ${values.join(",")}`);
  }

  async press(key: string): Promise<BrowserSnapshot> {
    return this.act(`press ${key}`);
  }

  async scroll(direction: "up" | "down"): Promise<BrowserSnapshot> {
    return this.act(`scroll ${direction}`);
  }

  async back(): Promise<BrowserSnapshot> {
    return this.act("back");
  }

  async screenshot() {
    return { data: TINY_JPEG, mimeType: "image/jpeg" as const, width: 1, height: 1 };
  }

  async extractText(): Promise<string> {
    return `Fake page at ${this.url}: three options (A, B, C). ${this.status}`.trim();
  }

  onFrame(listener: FrameListener): Unsubscribe {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  async close(): Promise<void> {
    this.listeners.clear();
  }

  private resolve(target: BrowserTarget): string {
    if (target.ref) {
      const index = Number(target.ref.replace(/^e/, "")) - 1;
      const element = ELEMENTS[index];
      if (element) return element.name;
    }
    return target.text ?? target.selector ?? "element";
  }

  private act(action: string): BrowserSnapshot {
    this.actions.push(action);
    for (const listener of [...this.listeners]) {
      listener({
        mimeType: "image/jpeg",
        data: TINY_JPEG,
        width: 1,
        height: 1,
        url: this.url,
        title: this.title(),
        ts: Date.now(),
      });
    }
    return this.render();
  }

  private title(): string {
    return this.url === "about:blank" ? "" : `Fake shop — ${new URL(this.url).hostname}`;
  }

  private render(): BrowserSnapshot {
    const lines = [
      `- heading "${this.title() || "Blank page"}" [level=1]`,
      ...ELEMENTS.map((element, i) => `- ${element.role} "${element.name}" [ref=e${i + 1}]`),
      ...(this.status ? [`- status "${this.status}"`] : []),
    ];
    return { url: this.url, title: this.title(), snapshot: lines.join("\n") };
  }
}

/** A 1×1 JPEG, base64. */
const TINY_JPEG =
  "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////wgALCAABAAEBAREA/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxA=";

// ── Execution provider ──────────────────────────────────────────────────────

export interface FakeExecutionOptions {
  shell?: boolean;
  /** A fake browser (or true for a new one). */
  browser?: boolean | FakeBrowser;
  /** Create real per-task workspace directories under this root (needed by Pi's file tools). */
  workspaceRoot?: string;
  /** Shell output per command (default: `ran: <command>`). */
  shellOutput?: (command: string) => Partial<ShellResult>;
}

export interface FakeExecution extends ExecutionProvider {
  readonly browser?: FakeBrowser;
  /** Shell commands executed, in order. */
  readonly commands: Array<{ command: string; cwd: string }>;
  readonly workspaces: string[];
  disposed: boolean;
}

export function createFakeExecution(options: FakeExecutionOptions = {}): FakeExecution {
  const browser = options.browser === true ? createFakeBrowser() : options.browser || undefined;
  const commands: Array<{ command: string; cwd: string }> = [];
  const workspaces: string[] = [];
  const execution: FakeExecution = {
    id: "fake",
    capabilities: { shell: options.shell ?? true, browser: browser !== undefined, computer: false },
    ...(browser ? { browser } : {}),
    commands,
    workspaces,
    disposed: false,
    shell: {
      async exec(command: string, execOptions: ShellExecOptions): Promise<ShellResult> {
        commands.push({ command, cwd: execOptions.cwd });
        const output = `ran: ${command}\n`;
        execOptions.onData?.(output);
        return {
          exitCode: 0,
          output,
          timedOut: false,
          truncated: false,
          durationMs: 1,
          ...options.shellOutput?.(command),
        };
      },
    },
    async prepareWorkspace(key: string): Promise<Workspace> {
      workspaces.push(key);
      if (!options.workspaceRoot) return { key, dir: `/tmp/ddl-fake-workspaces/${key}` };
      const dir = join(options.workspaceRoot, key);
      await mkdir(dir, { recursive: true });
      return { key, dir };
    },
    async dispose() {
      execution.disposed = true;
    },
  };
  return execution;
}

// ── Connectors (MCP) ────────────────────────────────────────────────────────

export interface SentMessage {
  server: string;
  tool: string;
  args: Record<string, unknown>;
}

export interface FakeConnectors extends ConnectorToolSource {
  /** Calls of non-read-only connector tools that went through (e.g. emails sent). */
  readonly effects: SentMessage[];
  /** Every call, read-only included. */
  readonly calls: SentMessage[];
  setState(server: string, state: ConnectorStatus["state"]): void;
}

export interface FakeConnectorServer {
  name: string;
  tools: McpToolDefinition[];
}

const DEFAULT_SERVERS: FakeConnectorServer[] = [
  {
    name: "mail",
    tools: [
      {
        name: "search_inbox",
        description: "Search the user's inbox.",
        inputSchema: {
          type: "object",
          properties: { query: { type: "string" } },
          required: ["query"],
        },
        annotations: { title: "Search inbox", readOnlyHint: true, openWorldHint: false },
      },
      {
        name: "send_email",
        description: "Send an email from the user's account.",
        inputSchema: {
          type: "object",
          properties: {
            to: { type: "string" },
            subject: { type: "string" },
            body: { type: "string" },
          },
          required: ["to", "subject", "body"],
        },
        annotations: { title: "Send email", destructiveHint: false, openWorldHint: true },
      },
    ],
  },
  {
    name: "calendar",
    tools: [
      {
        name: "list_events",
        description: "List calendar events in a date range.",
        inputSchema: {
          type: "object",
          properties: { from: { type: "string" }, to: { type: "string" } },
        },
        annotations: { title: "List events", readOnlyHint: true, openWorldHint: false },
      },
    ],
  },
];

export function createFakeConnectors(
  options: { servers?: FakeConnectorServer[] } = {},
): FakeConnectors {
  const servers = options.servers ?? DEFAULT_SERVERS;
  const effects: SentMessage[] = [];
  const calls: SentMessage[] = [];
  const states = new Map<string, ConnectorStatus["state"]>(
    servers.map((s) => [s.name, "connected"]),
  );
  const listeners = new Set<(status: ConnectorStatus[]) => void>();
  const status = (): ConnectorStatus[] =>
    servers.map((server) => ({
      name: server.name,
      transport: "stdio",
      state: states.get(server.name) ?? "connected",
      toolCount: server.tools.length,
    }));
  return {
    effects,
    calls,
    async getTools() {
      return servers
        .filter((server) => states.get(server.name) === "connected")
        .flatMap((server) =>
          server.tools.map((tool) =>
            createMcpToolSpec({
              name: `mcp__${server.name}__${tool.name}`,
              serverName: server.name,
              tool,
              target: {
                approval: () => "auto",
                async call(args) {
                  const record = { server: server.name, tool: tool.name, args };
                  calls.push(record);
                  if (tool.annotations.readOnlyHint !== true) effects.push(record);
                  return {
                    content: [
                      {
                        type: "text",
                        text: `${tool.name} ok (fake connector: nothing real happened)`,
                      },
                    ],
                  };
                },
              },
            }),
          ),
        );
    },
    status,
    onStatus(listener) {
      listeners.add(listener);
      return () => listeners.delete(listener);
    },
    async reload() {},
    async dispose() {
      listeners.clear();
    },
    setState(server, state) {
      states.set(server, state);
      for (const listener of [...listeners]) listener(status());
    },
  };
}

function escapeHtml(text: string): string {
  return text.replace(
    /[&<>"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!,
  );
}
