/**
 * Phrase vocabularies the UI rules match against element descriptions ("Place order button"),
 * form fields ("Card number") and typed text. Text is normalized first (`normalizePhrase`), so
 * patterns are written in lowercase with single spaces and match on word boundaries.
 */

/** Characters that render as nothing (soft hyphens, zero-width spaces/joiners, bidi controls, fillers). */
const INVISIBLE_RE = /\p{Cf}|\p{Default_Ignorable_Code_Point}/gu;

/** Cyrillic, Greek and IPA letters that look like Latin ones (`Plаce order` with a Cyrillic `а`). */
const CONFUSABLES: ReadonlyMap<string, string> = new Map(
  [
    "аa вb еe ёe кk мm нh оo рp сc тt уy хx ѕs іi їi јj ԁd ԛq ԝw һh үy ӏl",
    "АA ВB ЕE ЁE КK МM НH ОO РP СC ТT УY ХX ЅS ІI ЇI ЈJ ԚQ ԜW ҺH ҮY ӀI",
    "ɡg ıi ɑa οo αa εe ιi κk νv ρp τt υu χx ωw ϲc օo սu",
    "ΟO ΑA ΒB ΕE ΖZ ΗH ΙI ΚK ΜM ΝN ΡP ΤT ΥY ΧX ϹC",
  ]
    .join(" ")
    .split(" ")
    .map((pair) => [pair[0]!, pair[1]!] as const),
);

/** Folds lookalikes in words written only with Latin letters and lookalikes; real Cyrillic/Greek words stay. */
function foldConfusables(text: string): string {
  return text.replace(/\p{L}+/gu, (word) => {
    let folded = false;
    for (const ch of word) {
      if (CONFUSABLES.has(ch)) folded = true;
      else if (!/[A-Za-z]/.test(ch)) return word;
    }
    return folded ? [...word].map((ch) => CONFUSABLES.get(ch) ?? ch).join("") : word;
  });
}

/** Separates two readings of one text; no phrase pattern can match across it. */
const READINGS_SEPARATOR = " \n ";

function words(text: string): string {
  return text
    .toLowerCase()
    .replace(/[’‘`´]/g, "'")
    .replace(/[^\p{L}\p{N}$€£¥%&'+#@]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Lowercase, straight quotes, punctuation split into single spaces. Invisible characters are
 * removed (not split on), Latin accents are dropped (`réserver` → `reserver`) and lookalike
 * letters folded, so spelling tricks can't hide a phrase; letters of other scripts stay.
 * camelCase is ambiguous (`placeOrder` is two words, `PlAcE` is one), so when splitting it changes
 * the text, both readings are returned, joined by `READINGS_SEPARATOR`.
 */
export function normalizePhrase(text: string): string {
  const visible = foldConfusables(
    text
      .normalize("NFKC")
      .replace(INVISIBLE_RE, "")
      .normalize("NFKD")
      .replace(/(?<=[A-Za-z])\p{M}+/gu, "")
      .normalize("NFC"),
  );
  const split = words(visible.replace(/([a-z])([A-Z])/g, "$1 $2"));
  const whole = words(visible);
  return split === whole ? split : `${split}${READINGS_SEPARATOR}${whole}`;
}

function phrases(...alternatives: string[]): RegExp {
  return new RegExp(`(?:^| )(?:${alternatives.join("|")})(?= |$)`);
}

/** End of an element description (or of one reading), allowing a trailing widget word ("Share button"). */
const END = "(?: (?:button|btn|link|icon|tab|cta|control))?(?= \\n|$)";

// ── Clickable controls ──────────────────────────────────────────────────────

export const PAYMENT_CONTROL = phrases(
  "place (?:your |my |the |this )?order",
  "submit (?:your |my |the )?(?:order|payment)",
  "confirm (?:your |my |the |and )?(?:order|purchase|payment|pay|transfer)",
  "complete (?:your |my |the )?(?:order|purchase|payment|checkout|transaction|transfer)",
  "finish (?:checkout|purchase|order|payment)",
  "review and (?:place|pay|buy)",
  "buy(?: it| now| again| with [a-z ]+)?",
  "purchase(?! history| details| protection| summary)",
  "checkout",
  `check out(?: now| securely)?${END}`,
  "proceed to (?:checkout|payment|pay)",
  "continue to (?:checkout|payment)",
  "go to checkout",
  "pay(?: now| securely| with [a-z ]+| in full| bill| invoice| balance| total| rent| deposit| order)?",
  "apple pay",
  "google pay",
  "paypal(?: checkout)?",
  "venmo",
  "zelle",
  "cash app",
  "klarna",
  "afterpay",
  "order (?:now|it|this|again|online)",
  "reorder",
  "one click (?:buy|purchase|order)",
  "send (?:money|payment|funds)",
  "transfer (?:money|funds|now)",
  "wire(?: transfer| money| funds)?",
  "make (?:a )?payment",
  "authorize payment",
  "add (?:funds|money|credit|balance)",
  "top up",
  "cash out",
  "withdraw",
  "redeem(?: now| gift card| code)?",
  "place (?:a )?bid",
  "bid now",
  "make (?:an )?offer",
  "rent (?:now|it|this)",
  "tip",
  "leave a tip",
  "add (?:a )?tip",
  "donate(?: now)?",
  "donation",
  "pledge",
  "sponsor",
  "(?:transfer|send|wire|give|tip|donate|contribute|gift) (?:[$€£¥] ?\\d[\\d,.]*|\\d[\\d,.]* ?(?:[$€£¥]|usd|eur|gbp|chf|dollars?|euros?|pounds?))",
  `order${END}`,
  // Other languages (accents are stripped by normalizePhrase).
  `(?:jetzt |sofort |zahlungspflichtig |kostenpflichtig )?(?:kaufen|bestellen|bezahlen)${END}`,
  "zur kasse(?: gehen)?",
  "kauf abschlie(?:ss|ß)en",
  "bestellung (?:abschicken|absenden|aufgeben|abschlie(?:ss|ß)en)",
  "(?:nu )?(?:kopen|betalen|afrekenen)",
  "(?:koop|bestel|betaal) nu",
  "bestelling plaatsen|plaats bestelling",
  `commander${END}`,
  "(?:passer|valider|confirmer|finaliser) (?:la |ma |votre )?commande",
  "acheter(?: maintenant)?",
  `payer(?: maintenant)?${END}`,
  "(?:proceder|passer) au paiement",
  "(?:valider|confirmer) (?:le |mon |votre )?paiement",
  "comprar(?: ahora| ya| agora)?",
  "pagar(?: ahora| ya| agora)?",
  "(?:realizar|hacer|tramitar|confirmar|finalizar|fazer) (?:el |o )?pedido",
  "(?:finalizar|confirmar) (?:la |a )?compra",
  "confirmar (?:el |o )?pag(?:o|amento)",
  "ir a pagar",
  `(?:acquista|paga|ordina)${END}`,
  "(?:acquista|compra|paga|ordina) (?:ora|adesso|subito)",
  "(?:conferma|effettua|invia|concludi) (?:l'|il )?ordine",
  "procedi (?:all'acquisto|al pagamento|al checkout)",
  "купить(?: сейчас)?",
  "оформить заказ",
  "оплатить",
  "заказать",
  "\\S*(?:購入|注文|決済|支払|购买|購買|付款|支付|结账|結帳|下单|구매|주문|결제)\\S*",
);

export const SUBSCRIPTION_CONTROL = phrases(
  "subscribe(?! to (?:channel|newsletter))",
  "start (?:my |your |a |the )?(?:free )?trial",
  "try (?:it )?(?:free|for free)",
  "upgrade(?: now| plan| to [a-z ]+)?",
  "go premium",
  "get premium",
  "renew(?: now| plan| subscription| membership)?",
  "choose (?:this )?plan",
  "select (?:this )?plan",
  "(?:jetzt )?abonnieren",
  "s'abonner",
  "suscribirse",
  "abbonati",
  "assinar",
  "abonneren",
  "подписаться",
);

export const PAYMENT_METHOD_CONTROL = phrases(
  "add (?:a |an )?(?:new )?(?:payment method|card|credit card|debit card|bank account|bank)",
  "save (?:this |my )?(?:card|payment method)",
  "link (?:bank|card|bank account)",
  "update (?:payment|billing|card)(?: method| details| info)?",
);

export const BOOKING_CONTROL = phrases(
  "book(?: now| it| online| today| this| a [a-z]+| an [a-z]+| the [a-z]+| my [a-z]+| appointment| table| flight| flights| hotel| room| ticket| tickets| stay| trip| ride| session| class| slot| visit| tour| car| seat| seats| reservation| consultation| service| demo| lesson| court)?(?! review| club| store| shop| summary| cover)",
  "reserve(?: now| it| a [a-z]+| an [a-z]+| the [a-z]+| table| spot| seat| seats| room| ticket| tickets| your spot)?",
  "make (?:a |the )?reservation",
  "confirm (?:booking|reservation|appointment|slot|time|date|seat|seats|ticket|tickets|ride|pickup|trip|stay|visit)",
  "complete (?:booking|reservation)",
  "schedule(?: an| a| the| my| your)? (?:appointment|visit|call|meeting|consultation|pickup|delivery|service|tour|viewing|demo|session|exam|ride)",
  `schedule(?: it| now)?${END}`,
  "request (?:an |a )?(?:appointment|booking|reservation|visit|ride|pickup)",
  "request to book",
  "instant book",
  "rsvp",
  `attend(?: event| meeting| this)?${END}`,
  `(?:i'm |i am )?going${END}`,
  "register for (?:the |this )?(?:event|class|webinar|course|session|race)",
  "check ?in(?: now| online| for [a-z ]+)?",
  "web check ?in",
  "get boarding pass",
  "hold (?:this )?(?:seat|room|reservation|table)",
  `(?:jetzt |verbindlich |zahlungspflichtig )?(?:buchen|reservieren)${END}`,
  "termin (?:buchen|vereinbaren|reservieren)",
  "(?:nu )?(?:boeken|reserveren)",
  "boek nu",
  "reserver(?: maintenant)?",
  "confirmer (?:la |ma |votre )?reservation",
  "reservar(?: ahora| ya| agora)?",
  "confirmar (?:la |a )?reserva",
  "prenota(?:re)?(?: ora| adesso| subito)?",
  "conferma (?:la )?prenotazione",
  "забронировать",
  "\\S*(?:予約|预订|預訂|预约|預約|예약)\\S*",
);

export const BOOKING_CHANGE_CONTROL = phrases(
  "cancel (?:my |the |this |your )?(?:reservation|booking|appointment|flight|trip|stay|ticket|tickets|ride|visit|rsvp|event|class)",
  "(?:modify|change|update) (?:my |the |this )?(?:reservation|booking|appointment|flight|seat|date|time|trip)",
  "reschedule",
);

export const COMMUNICATION_CONTROL = phrases(
  "send(?! to (?:cart|bag|basket|wishlist))",
  "reply(?: all)?",
  "respond",
  "forward",
  "resend",
  "invite(?: [a-z]+)?",
  "invitation",
  "message (?:seller|host|owner|agent|landlord|them|him|her|us|provider|doctor|support|me|the [a-z]+)",
  "send (?:a )?message",
  "comment",
  "add (?:a )?comment",
  "post (?:a )?(?:comment|reply|answer|message)",
  "leave (?:a )?(?:comment|reply|message|voicemail)",
  `call(?: now| back| me| us| them| store| business)?${END}`,
  "text (?:me|us|them|now|seller|host)",
  "chat (?:now|with [a-z ]+)",
  "email (?:seller|host|owner|us|them|me|this|link|agent|support|the [a-z]+)",
  "share (?:via|by|with|to|on) (?:email|text|sms|message|messages|whatsapp|slack|messenger)",
  "notify [a-z]+",
  "direct message",
  "start (?:a )?(?:chat|conversation|call|video call)",
  "join (?:the )?(?:meeting|call|room|webinar|video|huddle)",
  "contact (?:seller|host|owner|agent|landlord)",
  `(?:nachricht )?(?:senden|absenden|abschicken|verschicken)${END}`,
  `antworten${END}`,
  "envoyer(?: le message| maintenant)?",
  "repondre",
  "enviar(?: mensaje| mensagem| ahora| agora)?",
  "invia(?:re)?(?: messaggio| ora)?",
  "rispondi",
  "verzenden|versturen|verstuur",
  "отправить",
  "ответить",
  "\\S*(?:送信|返信|发送|發送|回复|回覆|보내기|전송|답장)\\S*",
);

export const PUBLISHING_CONTROL = phrases(
  `post${END}`,
  "post (?:it|now|this|update|review|photo|video|story|publicly|to [a-z ]+|listing|ad|job|question|answer)",
  "publish(?: now| post| changes| article| page)?",
  "go live",
  "tweet",
  "retweet",
  "repost",
  "reblog",
  "quote tweet",
  `share(?: now| post| publicly| this| link)?${END}`,
  "share to (?:feed|timeline|story|profile|twitter|x|facebook|linkedin|instagram|reddit)",
  "submit (?:review|rating|feedback|answer|post|article|story|photo|listing|ad|question|comment)",
  "upload(?: photo| photos| file| files| video| resume| cv| document| image| images)?",
  "make (?:it )?public",
  `(?:like|unlike|follow|unfollow|connect|upvote|downvote|star|unstar|vote|endorse|clap|favorite|favourite|heart)(?: button| this| [a-z]+)?${END}`,
  "list (?:it|item|for sale)",
  "create (?:listing|post|ad)",
  "(?:jetzt )?(?:veroffentlichen|posten|teilen)",
  "publier|partager",
  "publicar|compartir|compartilhar",
  "pubblica(?:re)?|condividi",
  "publiceren",
  "опубликовать|поделиться",
  "\\S*(?:投稿|发布|發布|分享|게시|공유)\\S*",
);

export const ACCOUNT_CONTROL = phrases(
  "sign ?up(?: now| free| for free| with [a-z]+)?",
  "create (?:an |my |your |a new |new )?account",
  `register(?: now| account)?${END}`,
  "join (?:now|free|for free|today|us|the waitlist|waitlist)",
  "open (?:an |a )?account",
  "delete (?:my |your |this |the )?account",
  "close (?:my |your |this )?account",
  "deactivate(?: account)?",
  "cancel (?:my |your )?(?:account|membership|subscription|plan)",
  "(?:change|update|reset|set) (?:my |your |the )?(?:password|email|e mail|username|phone number|phone|security questions?|recovery (?:email|phone))",
  "new password",
  "(?:enable|disable|turn on|turn off|set up|setup|remove) (?:two ?factor|2fa|mfa|2 step|two step|authenticator|passkey|security key)",
  "two ?factor(?: authentication)?",
  "2fa",
  "unsubscribe(?: from [a-z ]+)?",
  "opt ?out",
  "stop (?:emails|notifications|messages)",
  `allow(?: access| all)?${END}`,
  "authorize(?! payment)",
  "grant (?:access|permission|permissions)",
  "give (?:access|permission)",
  "approve (?:access|request|login|sign ?in|device)",
  "accept (?:the )?(?:terms|agreement|invitation|invite|request|offer|policy|conditions|friend request|connection)",
  "i agree",
  "agree (?:and|&) (?:continue|proceed|submit|join)",
  "agree to (?:the )?(?:terms|policy|conditions)",
  "i accept",
  "link (?:account|accounts|wallet)",
  "connect (?:account|bank|wallet|google|apple|facebook|github|microsoft|slack|calendar)",
  "(?:sign|log) ?in with (?:google|apple|facebook|github|microsoft|twitter|x|linkedin)",
  "continue with (?:google|apple|facebook|github|microsoft)",
  "(?:sign|log) ?out (?:of|from) all(?: devices| sessions)?",
  "remove device",
  "revoke(?: access)?",
  "transfer ownership",
  "make (?:admin|owner)",
  "(?:add|remove) (?:member|user|collaborator|admin|owner)",
  "change (?:role|permissions)",
  "(?:jetzt )?registrieren|konto erstellen",
  "s'inscrire|creer (?:un |mon )?compte",
  "registrarse|crear (?:una |mi )?cuenta|criar (?:uma )?conta",
  "registrati|iscriviti",
  "registreren|account aanmaken",
  "зарегистрироваться",
);

export const DESTRUCTIVE_CONTROL = phrases(
  "delete(?! filter| filters)",
  "remove(?! filter| filters| from (?:cart|bag|basket|wishlist|list|compare|favorites)| selection| item from cart)",
  "erase",
  "wipe",
  "trash",
  "move to (?:the )?(?:trash|bin)",
  "empty (?:the )?(?:trash|bin|recycle bin)",
  "discard(?: changes| draft| all)?",
  "clear (?:all|history|data|browsing data|cache|conversation|chat|messages|everything)(?! filters)",
  "reset (?:all|settings|data|device|account|to (?:factory|default)s?)",
  "factory reset",
  "destroy",
  "purge",
  "permanently",
  "uninstall",
  "terminate",
  "(?:endgultig |dauerhaft )?loschen",
  "supprimer|effacer",
  "eliminar|borrar|excluir|apagar",
  "elimina(?:re)?|cancella(?:re)?",
  "verwijderen",
  "удалить",
  "\\S*(?:削除|删除|刪除|삭제)\\S*",
);

export const FORM_SUBMIT_CONTROL = phrases(
  "submit(?! search| query| filters?)",
  "confirm(?! location| age| email address)",
  "complete(?! profile later)",
  "finish",
  `apply(?: now| for [a-z ]+| to [a-z ]+)?${END}`,
  `sign(?: here| now| document| contract| agreement| and submit)?${END}`,
  "e ?sign",
  "adopt and sign",
  "save (?:changes|settings|profile|preferences|and continue|address|details)",
  "update (?:profile|settings|preferences|address|details|information|info)",
  `verify(?: account| identity| phone| email| me)?${END}`,
  "enroll(?: now)?",
  `claim(?: now| offer| reward| it)?${END}`,
  `activate(?: account| now| card)?${END}`,
  "request (?:a )?(?:quote|callback|info|information|demo|estimate)",
  "get (?:a )?(?:quote|estimate)",
  "yes,? (?:continue|proceed|confirm|i'm sure|delete|cancel|remove|send)",
  "i'm sure",
  "bestatigen|einreichen",
  "confirmer|valider|soumettre",
  "confirmar",
  "conferma(?:re)?",
  "bevestigen|indienen",
  "подтвердить",
  "\\S*(?:確定|确认|確認|提交)\\S*",
);

/** Controls that navigate, filter or reveal content without committing anything. */
export const BENIGN_CONTROL = phrases(
  "search(?: button| icon| bar| field)?",
  "find",
  "go",
  "next(?: page| step| slide| month| week| day| image| photo| result| results)?",
  "previous(?: page| month| week| image)?",
  "prev",
  "back",
  "more",
  "show more",
  "load more",
  "see more",
  "view more",
  "read more",
  "see all",
  "view all",
  "show all",
  "expand",
  "collapse",
  "show (?:details|less|replies|comments|results)",
  "view (?:details|profile|listing|product|menu|map|photos|reviews|order|cart|item|replies|comments|results|deal|offer|property|room|hotel|flight|fare)",
  "details",
  "more (?:info|information|details|options)",
  "learn more",
  "close",
  "dismiss",
  `cancel${END}`,
  "no thanks",
  "not now",
  "maybe later",
  "skip",
  "got it",
  "continue reading",
  "(?:accept|reject|decline|allow|deny|agree|manage|necessary|essential|only necessary)(?: all)? cookies?",
  "cookies?(?: settings| preferences| banner| consent| notice)?",
  "filters?",
  "(?:apply|clear|remove|reset) filters?",
  "sort(?: by [a-z ]+)?",
  "sort order",
  "price",
  "rating",
  "newest",
  "oldest",
  "relevance",
  "categor(?:y|ies)",
  "tab",
  "menu",
  "open menu",
  "navigation",
  "home",
  "logo",
  "page \\d+",
  "\\d+",
  "first page",
  "last page",
  "zoom(?: in| out)?",
  "map",
  "list view",
  "grid view",
  "photos?",
  "images?",
  "gallery",
  "play",
  "pause",
  "mute",
  "unmute",
  "full ?screen",
  "video",
  "thumbnail",
  "reviews?",
  "ratings?",
  "specifications",
  "specs",
  "description",
  "overview",
  "faq",
  "help",
  "about",
  "compare",
  "select (?:date|dates|size|color|colour|option|quantity|variant|language|currency|region|country)",
  "date picker",
  "calendar",
  "month",
  "increase",
  "decrease",
  "quantity",
  "add to (?:cart|bag|basket|wishlist|list|favorites|favourites|compare|collection)",
  "view cart",
  "cart",
  "open",
  "link",
  "article",
  "result",
  "headline",
  "story",
  "listing",
  "product",
  "item",
  "(?:sign|log) ?in",
  "(?:sign|log) ?out",
  "translate",
  "copy(?: link)?",
  "print",
  "download",
  "refresh",
  "reload",
  "retry",
  "try again",
  "directions",
  "website",
  "hours",
  "dropdown",
  "option",
);

// ── Form fields ─────────────────────────────────────────────────────────────

export const CREDENTIAL_FIELD = phrases(
  "password",
  "passcode",
  "passphrase",
  "pass code",
  "pin(?: code| number)?",
  "security answer",
  "one time (?:code|password|passcode|pin)",
  "otp",
  "verification code",
  "(?:2fa|mfa|two factor|authentication|auth) code",
  "secret(?: key| answer| question)?",
  "api key",
  "access key",
  "private key",
  "token",
  "seed phrase",
  "recovery (?:phrase|key|code)",
  "mnemonic",
  "wallet (?:phrase|key)",
  "passwort|kennwort|geheimzahl",
  "mot de passe",
  "contrasena|senha",
  "wachtwoord",
  "has[lł]o|sifre",
  "пароль",
  "\\S*(?:パスワード|暗証番号|密码|密碼|비밀번호)\\S*",
);

export const CARD_FIELD = phrases(
  "cvv2?",
  "cvc2?",
  "csc",
  "security code",
  "card (?:number|no|verification|details)",
  "credit card",
  "debit card",
  "cardholder(?: name)?",
  "name on card",
  "expir(?:y|ation)(?: date| month| year)?",
  "exp(?:iry)? (?:date|month|year)",
  "mm yy",
  "valid thru",
  "iban",
  "routing(?: number)?",
  "account number",
  "bank account",
  "sort code",
  "swift(?: code)?",
  "karten ?nummer|kartenprufnummer|prufnummer|prufziffer|sicherheitscode|karteninhaber",
  "ablaufdatum|gultig bis|bankleitzahl",
  "numero de (?:la )?carte|cryptogramme(?: visuel)?|code de securite|date d'expiration",
  "titulaire de la carte",
  "numero de (?:la )?tarjeta|codigo de seguridad|titular de la tarjeta",
  "fecha de (?:caducidad|vencimiento|expiracion)",
  "numero (?:della )?carta|codice di sicurezza|data di scadenza",
  "numero do cartao|codigo de seguranca|data de validade",
  "kaart ?nummer|vervaldatum",
  "номер карты",
  "\\S*(?:カード番号|セキュリティコード|卡号|卡號|安全码|카드 ?번호)\\S*",
);

/** ID numbers whose typed value is never displayed (a subset of the personal fields). */
export const ID_NUMBER_FIELD = phrases(
  "ssn",
  "social security",
  "passport",
  "tax id",
  "sozialversicherungsnummer|steuer ?(?:id|nummer|identifikationsnummer)|reisepass ?nummer",
  "numero de securite sociale|numero de passeport|numero de pasaporte|codice fiscale",
);

export const AMOUNT_FIELD = phrases(
  "amount",
  "(?:tip|donation|transfer|payment|send|gift) amount",
  "custom amount",
  "how much",
);

export const PERSONAL_FIELD = phrases(
  "ssn",
  "social security(?: number)?",
  "social insurance(?: number)?",
  "national (?:id|insurance|identity)(?: number)?",
  "tax (?:id|identification|file) (?:number)?",
  "tin",
  "ein",
  "itin",
  "passport(?: number| no)?",
  "driver'?s? licen[cs]e(?: number)?",
  "driving licen[cs]e(?: number)?",
  "licen[cs]e number",
  "id number",
  "identity (?:card|number)",
  "date of birth",
  "birth ?date",
  "dob",
  "birthday",
  "phone(?: number)?",
  "mobile(?: number| phone)?",
  "cell(?: phone| number)?",
  "telephone",
  "home address",
  "street(?: address)?",
  "address(?: line \\d)?",
  "mailing address",
  "billing address",
  "shipping address",
  "medical record(?: number)?",
  "insurance (?:id|member|policy|number)(?: number)?",
  "member id",
  "mother'?s maiden name",
  "geburtsdatum|sozialversicherungsnummer|steuer ?(?:id|nummer|identifikationsnummer)",
  "reisepass ?nummer|telefonnummer|handynummer",
  "date de naissance|numero de securite sociale|numero de passeport|numero de telephone",
  "fecha de nacimiento|numero de pasaporte|numero de telefono",
  "data di nascita|codice fiscale|numero di telefono",
  "data de nascimento|geboortedatum|telefoonnummer",
  "номер телефона|дата рождения",
);

/** Fields named "address" that are not a postal address. */
export const NON_POSTAL_ADDRESS = phrases(
  "e ?mail(?: address)?",
  "ip(?: address)?",
  "web address",
  "url",
  "wallet address",
);

export const SEARCH_FIELD = phrases(
  "search(?: box| bar| field| input| query)?",
  "query",
  "find",
  "filter",
  "look ?up",
  "keywords?",
  "where to",
  "where are you going",
  "destination",
  "going to",
  "from",
  "to",
  "origin",
  "departure",
  "arrival",
  "location",
  "city",
  "near",
  "zip(?: code)?",
  "postal code",
  "address bar",
  "url bar",
  "location bar",
  "omnibox",
  "what are you looking for",
  "promo(?: code)?",
  "coupon(?: code)?",
  "discount code",
  "gift card code",
  "quantity",
);

export const MESSAGE_FIELD = phrases(
  "message",
  "reply",
  "comment",
  "chat",
  "compose",
  "body",
  "email body",
  "write (?:a )?(?:message|reply|comment|review|post)",
  "what's on your mind",
  "post",
  "tweet",
  "review",
  "status",
  "caption",
  "note to [a-z ]+",
  "text message",
  "dm",
);

export const CONTACT_FIELD = phrases(
  "e ?mail(?: address)?",
  "name",
  "first name",
  "last name",
  "full name",
  "company",
  "username",
  "user ?name",
  "login",
);

export const TERMINAL_FIELD = phrases(
  "terminal",
  "console",
  "shell",
  "command(?: line)?",
  "cli",
  "cloud shell",
  "ssh",
);

// ── Intent and free text ────────────────────────────────────────────────────

/** Task/rationale wording that suggests the agent is about to commit something. */
export const COMMITTING_INTENT = phrases(
  "buy",
  "purchase",
  "order (?:a|an|the|some|more|food|pizza|groceries|takeout|online|it|them|new|me)",
  "pay(?: for| the| my| rent| bill| invoice)?",
  "checkout",
  "book(?: a| an| the| my| me| appointment| flight| flights| hotel| table| ticket| tickets)?",
  "reserve",
  "schedule (?:a |an |the |my )?(?:appointment|meeting|call|visit|pickup|delivery)",
  "rsvp",
  "send",
  "email (?:to|the|my|him|her|them|back)",
  "message (?:the|my|him|her|them)",
  "text (?:the|my|him|her|them|mom|dad)",
  "reply",
  "respond",
  "post (?:on|to|a|an|the|my)",
  "publish",
  "tweet",
  "sign up",
  "register",
  "subscribe",
  "unsubscribe",
  "cancel",
  "delete",
  "donate",
  "apply (?:for|to)",
  "submit",
  "transfer",
  "wire",
  "log ?in",
  "sign ?in",
  "confirm",
  "kaufen|bestellen|buchen|reservieren|bezahlen|senden",
  "acheter|commander|reserver|payer|envoyer",
  "comprar|pedir|reservar|pagar|enviar",
  "acquistare|ordinare|prenotare|pagare|inviare",
);

/** Free text that asks for or announces a money transfer (also a classic prompt-injection payload). */
export const MONEY_TRANSFER_TEXT: readonly RegExp[] = [
  /\b(?:wire|transfer|send|pay|remit|venmo|zelle|paypal)\b[^.\n]{0,40}?(?:[$€£¥]\s?\d|\b\d[\d,.]*\s?(?:usd|eur|gbp|dollars|euros|pounds|btc|eth|usdt|bitcoin)\b)/i,
  /\b(?:gift ?cards?|itunes cards?|google play cards?|steam cards?)\b[^.\n]{0,60}\b(?:codes?|numbers?|pins?)\b/i,
  /\b(?:bitcoin|btc|eth|ethereum|crypto|usdt) (?:wallet|address)\b/i,
  /\b(?:routing|account) number\b[^.\n]{0,30}\d{6,}/i,
];
