import * as domain from "./domain";
import * as errors from "./errors";
import * as events from "./events";
import * as rest from "./rest";
import * as settings from "./settings";

/** Every named wire schema by name (the `$defs` of the JSON Schema export). */
export const WIRE_SCHEMAS = {
  // Domain
  TaskAgentStatus: domain.TaskAgentStatusSchema,
  TaskAgentRecord: domain.TaskAgentRecordSchema,
  RiskLevel: domain.RiskLevelSchema,
  ActionCategory: domain.ActionCategorySchema,
  ApprovalScope: domain.ApprovalScopeSchema,
  ApprovalDecision: domain.ApprovalDecisionSchema,
  ApprovalStatus: domain.ApprovalStatusSchema,
  ApprovalRequest: domain.ApprovalRequestSchema,
  ArtifactKind: domain.ArtifactKindSchema,
  ArtifactMeta: domain.ArtifactMetaSchema,
  MessageAuthor: domain.MessageAuthorSchema,
  TextMessage: domain.TextMessageSchema,
  ToolCallStatus: domain.ToolCallStatusSchema,
  ToolCallMessage: domain.ToolCallMessageSchema,
  ApprovalMessage: domain.ApprovalMessageSchema,
  ArtifactMessage: domain.ArtifactMessageSchema,
  StatusMessage: domain.StatusMessageSchema,
  ThreadMessage: domain.ThreadMessageSchema,
  SurfaceKind: domain.SurfaceKindSchema,
  Thread: domain.ThreadSchema,
  ThreadSummary: domain.ThreadSummarySchema,
  SurfaceFrameAction: domain.SurfaceFrameActionSchema,
  SurfaceFrame: domain.SurfaceFrameSchema,
  // Settings
  ThemePreference: settings.ThemePreferenceSchema,
  EditorSettings: settings.EditorSettingsSchema,
  DailyNoteSettings: settings.DailyNoteSettingsSchema,
  WeeklyNoteSettings: settings.WeeklyNoteSettingsSchema,
  AgentWatchWindow: settings.AgentWatchWindowSchema,
  AgentHarnessKind: settings.AgentHarnessKindSchema,
  AgentSettings: settings.AgentSettingsSchema,
  AppSettings: settings.AppSettingsSchema,
  UpdateSettingsRequest: settings.UpdateSettingsRequestSchema,
  // REST
  AgentMode: rest.AgentModeSchema,
  HealthResponse: rest.HealthResponseSchema,
  VaultEntry: rest.VaultEntrySchema,
  VaultTreeResponse: rest.VaultTreeResponseSchema,
  NoteResponse: rest.NoteResponseSchema,
  WriteNoteRequest: rest.WriteNoteRequestSchema,
  WriteNoteResponse: rest.WriteNoteResponseSchema,
  RenameRequest: rest.RenameRequestSchema,
  FolderRenameResponse: rest.FolderRenameResponseSchema,
  RenameResponse: rest.RenameResponseSchema,
  CreateFolderRequest: rest.CreateFolderRequestSchema,
  CreateFolderResponse: rest.CreateFolderResponseSchema,
  TrashResponse: rest.TrashResponseSchema,
  OkResponse: rest.OkResponseSchema,
  ThreadActionResponse: rest.ThreadActionResponseSchema,
  DailyNoteResponse: rest.DailyNoteResponseSchema,
  SearchHit: rest.SearchHitSchema,
  SearchResponse: rest.SearchResponseSchema,
  SettingsResponse: rest.SettingsResponseSchema,
  ConnectorStatus: rest.ConnectorStatusSchema,
  ExecutionStatus: rest.ExecutionStatusSchema,
  AgentStatusResponse: rest.AgentStatusResponseSchema,
  SetAgentEnabledRequest: rest.SetAgentEnabledRequestSchema,
  TaskRecordsResponse: rest.TaskRecordsResponseSchema,
  ThreadListResponse: rest.ThreadListResponseSchema,
  ThreadResponse: rest.ThreadResponseSchema,
  PostMessageRequest: rest.PostMessageRequestSchema,
  ApprovalListResponse: rest.ApprovalListResponseSchema,
  ApprovalResponse: rest.ApprovalResponseSchema,
  ApprovalDecisionRequest: rest.ApprovalDecisionRequestSchema,
  ConnectorsResponse: rest.ConnectorsResponseSchema,
  // Errors
  ApiErrorCode: errors.ApiErrorCodeSchema,
  ApiErrorBody: errors.ApiErrorBodySchema,
  ConflictResponse: errors.ConflictResponseSchema,
  ApprovalConflictResponse: errors.ApprovalConflictResponseSchema,
  // WebSocket
  VaultChangeOrigin: events.VaultChangeOriginSchema,
  VaultChange: events.VaultChangeSchema,
  WsErrorCode: events.WsErrorCodeSchema,
  ServerHelloEvent: events.ServerHelloEventSchema,
  VaultChangedEvent: events.VaultChangedEventSchema,
  TaskRecordsEvent: events.TaskRecordsEventSchema,
  TaskRecordEvent: events.TaskRecordEventSchema,
  ThreadUpsertEvent: events.ThreadUpsertEventSchema,
  ThreadMessageEvent: events.ThreadMessageEventSchema,
  ThreadDeltaEvent: events.ThreadDeltaEventSchema,
  ApprovalUpsertEvent: events.ApprovalUpsertEventSchema,
  AgentStatusEvent: events.AgentStatusEventSchema,
  SurfaceFrameEvent: events.SurfaceFrameEventSchema,
  SettingsChangedEvent: events.SettingsChangedEventSchema,
  ServerErrorEvent: events.ServerErrorEventSchema,
  ServerEvent: events.ServerEventSchema,
  ClientHelloEvent: events.ClientHelloEventSchema,
  ClientPingEvent: events.ClientPingEventSchema,
  SurfaceSubscribeEvent: events.SurfaceSubscribeEventSchema,
  SurfaceUnsubscribeEvent: events.SurfaceUnsubscribeEventSchema,
  ThreadReadEvent: events.ThreadReadEventSchema,
  EditorActivityEvent: events.EditorActivityEventSchema,
  ClientEvent: events.ClientEventSchema,
} as const;

export type WireSchemaName = keyof typeof WIRE_SCHEMAS;

/**
 * Request-side schemas: strict (unknown keys rejected). Everything else is a response or event
 * and tolerates unknown keys.
 */
export const REQUEST_SCHEMA_NAMES = [
  "UpdateSettingsRequest",
  "WriteNoteRequest",
  "RenameRequest",
  "CreateFolderRequest",
  "SetAgentEnabledRequest",
  "PostMessageRequest",
  "ApprovalDecisionRequest",
  "ClientHelloEvent",
  "ClientPingEvent",
  "SurfaceSubscribeEvent",
  "SurfaceUnsubscribeEvent",
  "ThreadReadEvent",
  "EditorActivityEvent",
  "ClientEvent",
] as const satisfies readonly WireSchemaName[];
